### ISSUE TITLE
obc-peer gets crashed after some invoke/query requestes processed

### ISSUE THREAD

**Issue by samding01** [hyperledger-archives/fabric#1033]
Start a 4 peers with docker-composer,  setting as consensus =obcpbft, batch. no security. After processing some invokes and queries, one of container crashed, here is the log:

```
  fatal error: concurrent map read and map write

  goroutine 55814 [running]:
  runtime.throw(0x766740, 0x21)
    /usr/local/go/src/runtime/panic.go:530 +0xae fp=0xc8204db5a8 sp=0xc8204db590
 runtime.mapaccess1_faststr(0x538ee0, 0xc820178690, 0xc8202b8d50, 0x24, 0x2)
    /usr/local/go/src/runtime/hashmap_fast.go:202 +0x80 fp=0xc8204db608 sp=0xc8204db5a8
 github.com/openblockchain/obc-peer/openchain/chaincode/shim.  (*Handler).handlePutState(0xc8201ea230, 0xc82022ade7, 0x1, 0xc82022af78, 0x4, 0x8,  0xc8202b8d50, 0x24, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/chaincode/shim/handler.go:482  +0x264 fp=0xc8204dbac8 sp=0xc8204db608
  github.com/openblockchain/obc-peer/openchain/chaincode/shim. (*ChaincodeStub).PutState(0xc8202231e0, 0xc82022ade7, 0x1, 0xc82022af78, 0x4, 0x8, 0x0, 0x0)
     /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/chaincode /shim/chaincode.go:254 +0x7c fp=0xc8204dbb20 sp=0xc8204dbac8
 main.(*SimpleChaincode).invoke(0x9ffb88, 0xc8202231e0, 0xc820305640, 0x3, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/example/chaincode  /chaincode_example02/chaincode_example02.go:119 +0xa08 fp=0xc8204dbd00 sp=0xc8204dbb20
  main.(*SimpleChaincode).Run(0x9ffb88, 0xc8202231e0, 0xc82022ade0, 0x6, 0xc820305640, 0x3, 0x4, 0x0, 0x0, 0x0, ...)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example02/chaincode_example02.go:154 +0x190 fp=0xc8204dbd80 sp=0xc8204dbd00
 github.com/openblockchain/obc-peer/openchain/chaincode/shim.(*Handler).handleTransaction.func1(0xc8201ea230, 0xc820305540)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/chaincode/shim/handler.go:294  +0x65e fp=0xc8204dbf88 sp=0xc8204dbd80
 runtime.goexit()
    /usr/local/go/src/runtime/asm_s390x.s:925 +0x2 fp=0xc8204dbf88 sp=0xc8204dbf88
  created by github.com/openblockchain/obc-peer/openchain/chaincode/shim. (*Handler).handleTransaction
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/chaincode/shim/handler.go:310 +0x4e

  goroutine 1 [chan receive]:
  github.com/openblockchain/obc-peer/openchain/chaincode/shim.chatWithPeer(0x3ffa9bf01e0,   0xc82012e138, 0x3ffa9bb4208, 0x9ffb88, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/chaincode /shim/chaincode.go:222 +0x9d8
    github.com/openblockchain/obc-peer/openchain/chaincode/shim.Start(0x3ffa9bb4208, 0x9ffb88, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/chaincode/shim/chaincode.go:92 +0x6ca
   main.main()
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/example/chaincode /chaincode_example02/chaincode_example02.go:199 +0xc4
```

This happens on LoZ, almost every time gets crashed before processing 10k requests

**Comment by tuand27613** [comment]
which commit level are you running with ?  I see paths like obc-peer/openchain/chaincode which points to the old obc-peer repo.

Could you retry from the hyperledger/fabric repo ?

**Comment by muralisrini** [comment]
@tuand27613 @samding01 : this is probably a bug common to both bases. But I agree with @tuand27613 . Try on hyperledger please. You woud have to change your Chaincode to confirm to new interface as specified in https://github.com/hyperledger/fabric/wiki/Sprint-Release-Notes

**Comment by samding01** [comment]
it is the latest main branch, commit dc47c504733b1d2e4a9bebc3fa86e5516a8475eb
I will try hyperledger.

**Comment by samding01** [comment]
Tested the latest code, the crash is gone.  Close this issue.  Thanks.
