### ISSUE TITLE
Peer CLI fails to run when invoked outside its directory

### ISSUE THREAD

**Issue by lehors** [hyperledger-archives/fabric#1224]
When invoked from anywhere else than the fabric/peer directory the peer command fails because it can't find the configuration files that are all searched for using relative paths.

```
vagrant@hyperledger-devenv:v0.0.9-4ba4f96:/opt/gopath/src/github.com/hyperledger/fabric$ peer/peer
panic: Error reading CORE_PBFT plugin config: Unsupported Config Type ""

goroutine 1 [running]:
panic(0xcac6a0, 0xc8201a6f30)
        /opt/go/src/runtime/panic.go:464 +0x3e6
github.com/hyperledger/fabric/consensus/obcpbft.loadConfig(0xc820156a90)
        /opt/gopath/src/github.com/hyperledger/fabric/consensus/obcpbft/obc-pbft.go:83 +0x601
...
```

**Comment by lehors** [comment]
Fixed with PR  #1229
