### ISSUE TITLE
panic: concurrent map writes in crypto.(*peerImpl).getEnrollmentCert

### ISSUE THREAD

**Issue by corecode** [hyperledger-archives/fabric#1291]
Running slightly older master (d5d1c8576b714a7a7ab4f3b5dbacbe4619d209e2).

```
09:57:34.522 [crypto] register -> INFO 075[0m [client.test_user3] Register crypto engine...
09:57:34.522 [crypto] register -> INFO 076[0m [client.test_user3] Register crypto engine...done.
09:57:34.522 [crypto] Login -> INFO 077[0m Registering client [test_user3] with name [test_user3]...done!
09:57:34.523 [rest] Register -> INFO 078[0m Storing login token for user 'test_user3'.
09:57:34.523 [rest] Register -> INFO 079[0m Login successful for user 'test_user3'.
fatal error: concurrent map writes

goroutine 76 [running]:
runtime.throw(0xed0930, 0x15)
    /opt/go/src/runtime/panic.go:530 +0x90 fp=0xc82035f3f8 sp=0xc82035f3e0
runtime.mapassign1(0xbc6460, 0xc82042a990, 0xc82035f558, 0xc82035f500)
    /opt/go/src/runtime/hashmap.go:445 +0xb1 fp=0xc82035f4a0 sp=0xc82035f3f8
github.com/hyperledger/fabric/core/crypto.(*peerImpl).getEnrollmentCert(0xc8203cb1e0, 0xc8201fed60, 0x20, 0x20, 0xbc9be0, 0x0, 0x0)
    /opt/gopath/src/github.com/hyperledger/fabric/core/crypto/peer_eca.go:61 +0x9c1 fp=0xc82035f5b8 sp=0xc82035f4a0
github.com/hyperledger/fabric/core/crypto.(*validatorImpl).Verify(0xc8203cb1c0, 0xc8201fed60, 0x20, 0x20, 0xc820302e60, 0x47, 0x47, 0xc8203a7950, 0x85, 0x85, ...)
    /opt/gopath/src/github.com/hyperledger/fabric/core/crypto/validator_impl.go:115 +0x172 fp=0xc82035f670 sp=0xc82035f5b8
github.com/hyperledger/fabric/core/peer.(*Handler).beforeHello(0xc8203bcb60, 0xc8203bd6c0)
    /opt/gopath/src/github.com/hyperledger/fabric/core/peer/handler.go:162 +0x794 fp=0xc82035f818 sp=0xc82035f670
github.com/hyperledger/fabric/core/peer.NewPeerHandler.func2(0xc8203bd6c0)
    /opt/gopath/src/github.com/hyperledger/fabric/core/peer/handler.go:80 +0x2a fp=0xc82035f830 sp=0xc82035f818
github.com/hyperledger/fabric/vendor/github.com/looplab/fsm.(*FSM).beforeEventCallbacks(0xc820205ce0, 0xc8203bd6c0, 0x0, 0x0)
    /opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/looplab/fsm/fsm.go:290 +0xb4 fp=0xc82035f880 sp=0xc82035f830
github.com/hyperledger/fabric/vendor/github.com/looplab/fsm.(*FSM).Event(0xc820205ce0, 0xe474b0, 0xa, 0xc82016f6f0, 0x1, 0x1, 0x0, 0x0)
    /opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/looplab/fsm/fsm.go:242 +0x596 fp=0xc82035f9c0 sp=0xc82035f880
github.com/hyperledger/fabric/core/peer.(*Handler).HandleMessage(0xc8203bcb60, 0xc8202bde40, 0x0, 0x0)
    /opt/gopath/src/github.com/hyperledger/fabric/core/peer/handler.go:258 +0x5a9 fp=0xc82035fb20 sp=0xc82035f9c0
github.com/hyperledger/fabric/consensus/helper.(*ConsensusHandler).HandleMessage(0xc8202239a0, 0xc8202bde40, 0x0, 0x0)
    /opt/gopath/src/github.com/hyperledger/fabric/consensus/helper/handler.go:86 +0x3d2 fp=0xc82035fc28 sp=0xc82035fb20
github.com/hyperledger/fabric/core/peer.(*PeerImpl).handleChat(0xc820431480, 0x7f2880cf8078, 0xc8200165e0, 0x7f2880d753e0, 0xc8201d8d60, 0x1, 0x0, 0x0)
    /opt/gopath/src/github.com/hyperledger/fabric/core/peer/peer.go:526 +0x672 fp=0xc82035fd88 sp=0xc82035fc28
github.com/hyperledger/fabric/core/peer.(*PeerImpl).chatWithPeer(0xc820431480, 0xc8204254b0, 0x10, 0x0, 0x0)
    /opt/gopath/src/github.com/hyperledger/fabric/core/peer/peer.go:495 +0xa01 fp=0xc82035ff58 sp=0xc82035fd88
runtime.goexit()
    /opt/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82035ff60 sp=0xc82035ff58
created by github.com/hyperledger/fabric/core/peer.(*PeerImpl).PeersDiscovered
    /opt/gopath/src/github.com/hyperledger/fabric/core/peer/peer.go:339 +0x378
```

**Comment by adecaro** [comment]
@corecode just submitted PR #1292 to address the issue. May you give a look at it? Thanks :)

**Comment by corecode** [comment]
the patch looks reasonable.  I don't know if I will ever be able to reproduce this panic.  I'll close this issue in anticipation of the PR being merged.

Thanks!
