### ISSUE TITLE
Membersvc can't write to disk, causes panic

### ISSUE THREAD

**Issue by RicHernandez2** [hyperledger-archives/fabric#1332]
Description:

membersvc executable is started, cannot write to disk, panics

Steps to repro:
1.  Git clone latest code
2.  Edit core.yaml to turn on security and privacy, rename ID to vp0, set consensus to pbft
3.  Edit config.yaml in obcpbft dir to use sieve
4.  Edit membersrvc.yaml adding 0 to the end of username vp
5.  Vagrant up
6.  Vagrant ssh
7.  go build in membersvc directory
8.  Run ./membersvc

Results:

membersvc tried to make directories, can't make them, panics

Expected results:

membersvc should be able to make those directories and write to them

```
    default: Guest Additions Version: 4.3.36
    default: VirtualBox Version: 5.0
==> default: Mounting shared folders...
    default: /vagrant => C:/Go/src/github.com/hyperledger/fabric/devenv
    default: /local-dev => C:/Go/src/github.com/hyperledger/fabric
    default: /hyperledger => C:/Go/src/github.com/hyperledger/fabric
    default: /opt/gopath/src/github.com/hyperledger/fabric => C:/Go/src/github.com/hyperledger/fabric
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: ++ export DOCKER_STORAGE_BACKEND=
==> default: ++ DOCKER_STORAGE_BACKEND=
==> default: ++ cd /hyperledger/devenv
==> default: ++ ./setup.sh
==> default: E: Unable to synchronize mmap - msync (5: Input/output error)
==> default: E: The package lists or status file could not be parsed or opened.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

RicHernandez@IBM155-R90BK47B MINGW64 /c/go/src/github.com/hyperledger/fabric/devenv (master)
$ vagrant ssh
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-85-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Tue May  3 13:48:13 UTC 2016

  System load:  0.5               Processes:           92
  Usage of /:   4.4% of 38.75GB   Users logged in:     0
  Memory usage: 2%                IP address for eth0: 10.0.2.15
  Swap usage:   0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/

vagrant@ubuntu-1404:~$ cd $GOPATH/src
vagrant@ubuntu-1404:/opt/gopath/src$ cd github.com/hyperledger/fabric/
vagrant@ubuntu-1404:/opt/gopath/src/github.com/hyperledger/fabric$ ls
bddtests  consensus  CONTRIBUTING.md  core  devenv  docs  events  examples  LICENSE  MAINTAINERS.txt  membersrvc  peer  protos  README.md  scripts  sdk  vendor
vagrant@ubuntu-1404:/opt/gopath/src/github.com/hyperledger/fabric$ cd membersrvc/
vagrant@ubuntu-1404:/opt/gopath/src/github.com/hyperledger/fabric/membersrvc$ go build
vagrant@ubuntu-1404:/opt/gopath/src/github.com/hyperledger/fabric/membersrvc$ ./membersrvc
2016/05/03 14:16:35 Log level not recognized '', defaulting to DEBUG: logger: invalid log level
2016/05/03 14:16:35 Working at security level [256]
INFO: 2016/05/03 14:16:35 CA Server (0.1)
INFO: 2016/05/03 14:16:35 Fresh start; creating databases, key pairs, and certificates.
PANIC: 2016/05/03 14:16:35 ca.go:172: mkdir /var/hyperledger: permission denied
panic: mkdir /var/hyperledger: permission denied


goroutine 1 [running]:
panic(0x992b40, 0xc820190f80)
        /opt/go/src/runtime/panic.go:464 +0x3e6
log.(*Logger).Panicln(0xc82013d9f0, 0xc82012d8f0, 0x1, 0x1)
        /opt/go/src/log/log.go:220 +0xbf
github.com/hyperledger/fabric/membersrvc/ca.NewCA(0xb69be8, 0x3, 0x0)
        /opt/gopath/src/github.com/hyperledger/fabric/membersrvc/ca/ca.go:172 +0x387
github.com/hyperledger/fabric/membersrvc/ca.NewECA(0xc82013d900)
        /opt/gopath/src/github.com/hyperledger/fabric/membersrvc/ca/eca.go:79 +0x63
main.main()
        /opt/gopath/src/github.com/hyperledger/fabric/membersrvc/server.go:82 +0xafb
vagrant@ubuntu-1404:/opt/gopath/src/github.com/hyperledger/fabric/membersrvc$
```

**Comment by RicHernandez2** [comment]
Problem occurred during Vagrant up, doing Vagrant Destroy and Up again to see if it repros.

**Comment by RicHernandez2** [comment]
After second Vagrant up, no repro
