### ISSUE TITLE
Consensus sieve has error on both LoZ and X86 platforms -- one peer cannot get block 

### ISSUE THREAD

**Issue by samding01** [hyperledger-archives/fabric#1538]
## Description

Get the latest hyper ledger code (commit 66ca505deb06f4df024f0540d18bfdecb04584fa )
Run with busywork and get error from peers. After tested with @bcbrock , he confirmed that this is bug with  sieve on LoZ platform.
## Describe How to Reproduce

1) Get the latest hyper ledger code;
2) Build peer ;
3) run "make stress2s" from folder "$GPATHsrc/github.com/hyperledger/fabric/tools/busywork/counters"

Error msg:

```
 ...
 driver:     Client 0 is subprocess 49966
 driver: Waiting (indefinitely) for subprocesses to complete
 fabricLogger:ERROR: Block 2206 JSON response does not parse
 fabricLogger:ERROR: HTTP 'ncode' = '200'
 fabricLogger:ERROR: Full HTTP token dump below; Aborting
 fabricLogger:ERROR:     sock socka8d15a80
 fabricLogger:ERROR:     http HTTP/1.1 200 OK
 fabricLogger:ERROR:     querylength 0
 fabricLogger:ERROR:     -queryblocksize 8192
 fabricLogger:ERROR:     state body
 fabricLogger:ERROR:     charset iso8859-1
 fabricLogger:ERROR:     type application/json
 fabricLogger:ERROR:     -binary false
 fabricLogger:ERROR:     url http://0.0.0.0:48106/chain/blocks/2206
 fabricLogger:ERROR:     -keepalive 0
 fabricLogger:ERROR:     -timeout 0
 fabricLogger:ERROR:     socketinfo 0.0.0.0:48106
 fabricLogger:ERROR:     queryoffset 0
 fabricLogger:ERROR:     binary 1
 fabricLogger:ERROR:     -strict 1
 fabricLogger:ERROR:     totalsize 5
 fabricLogger:ERROR:     -validate 0
 fabricLogger:ERROR:     -protocol 1.1
 fabricLogger:ERROR:     connection close
 fabricLogger:ERROR:     -queryprogress
 fabricLogger:ERROR:     -headers
 fabricLogger:ERROR:     -blocksize 8192
 fabricLogger:ERROR:     coding
 fabricLogger:ERROR:     status ok
 fabricLogger:ERROR:     body null

 fabricLogger:ERROR:     currentsize 5
```

Then use `url http://localhost:<peer REST port>/chain/blocks/3` to find it returns "null" from vp3 only,
All 4 vps are running.

Here is error
[vps_log.zip](https://github.com/hyperledger/fabric/files/274937/vps_log.zip)
 log from vps

**Comment by bcbrock** [comment]
This issue is similar to issues we continue to see with PBFT batch, where blocks are being reported back through the REST API that contain no transactions. Here Sam is getting a completely NULL response from peer 3, but the other peers correctly report the block. 

I can't reproduce this issue on my X86 server, where Sieve appears to be working for me. This issue may be arising because the Z system is so fast, or other timing aspects particular to Z may expose different kinds of race conditions.

Note: Regarding speed, busywork logs the peer at WARNING level by default. Because DEBUG level logging now generates such humongous amounts of data, the network throughput (hence stress) is 2x to 3x greater here than in a run with DEBUG level logging enabled.

**Comment by samding01** [comment]
Tested on a x-86 host, got the similar error:

```
...   
driver: Waiting up to 60s for array creation to be registered
driver: Spawning clients:
driver:     Client 0 is subprocess 5591
driver: Waiting (indefinitely) for subprocesses to complete
fabricLogger:ERROR: REST API call to 0.0.0.0:36008 for block 1574 failed with 0 retries
fabricLogger:ERROR: HTTP 'ncode' = ''
fabricLogger:ERROR: Full HTTP token dump below; Aborting
fabricLogger:ERROR:     sock sock9600ee0
fabricLogger:ERROR:     http
fabricLogger:ERROR:     querylength 0
fabricLogger:ERROR:     -queryblocksize 8192
fabricLogger:ERROR:     state connecting
fabricLogger:ERROR:     charset iso8859-1
fabricLogger:ERROR:     type text/html
fabricLogger:ERROR:     -binary false
fabricLogger:ERROR:     url http://0.0.0.0:36008/chain/blocks/1574
fabricLogger:ERROR:     -keepalive 0
fabricLogger:ERROR:     -timeout 0
fabricLogger:ERROR:     socketinfo 0.0.0.0:36008
fabricLogger:ERROR:     queryoffset 0
fabricLogger:ERROR:     binary 0
fabricLogger:ERROR:     -strict 1
fabricLogger:ERROR:     totalsize 0
fabricLogger:ERROR:     -validate 0
fabricLogger:ERROR:     -protocol 1.1
fabricLogger:ERROR:     connection close
fabricLogger:ERROR:     -queryprogress
fabricLogger:ERROR:     -headers
fabricLogger:ERROR:     -blocksize 8192
fabricLogger:ERROR:     coding
fabricLogger:ERROR:     status ok
fabricLogger:ERROR:     body
fabricLogger:ERROR:     currentsize 0
fabricLogger:ERROR:     meta
fabricLogger:ERROR:     -type application/x-www-form-urlencoded
Makefile:92: recipe for target 'stress2s' failed
```

Here is full vp log 
[sieve_error_log_x86.zip](https://github.com/hyperledger/fabric/files/275339/sieve_error_log_x86.zip)

**Comment by bcbrock** [comment]
@samding01 What kind of X86 system are you running on? Processor family, cores, frequency etc?

**Comment by samding01** [comment]
@bcbrock  SUSE Linux Enterprise Server 12  (x86_64)

**Comment by bcbrock** [comment]
@samding01 Peer 2 crashed in your logs:

```
[33m15:29:28.824 [peer] beforeSyncBlocks -> WARN 251[0m Ignoring SyncBlocks message with correlationId = 3, blocks 1344 to 1344, as current correlationId = 4
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x9faa97]

goroutine 11 [running]:
github.com/hyperledger/fabric/consensus/obcpbft.(*pbftCore).execDoneSync(0xc820077ce0)
    /gsa/tlbgsa/home/s/a/samding/web/public/workplace/fab/src/github.com/hyperledger/fabric/consensus/obcpbft/pbft-core.go:902 +0x247
github.com/hyperledger/fabric/consensus/obcpbft.(*pbftCore).main(0xc820077ce0)
    /gsa/tlbgsa/home/s/a/samding/web/public/workplace/fab/src/github.com/hyperledger/fabric/consensus/obcpbft/pbft-core.go:299 +0x886
created by github.com/hyperledger/fabric/consensus/obcpbft.newPbftCore
    /gsa/tlbgsa/home/s/a/samding/web/public/workplace/fab/src/github.com/hyperledger/fabric/consensus/obcpbft/pbft-core.go:255 +0x167d
```

I reran just now and I also saw the same failure on the terminal, however I stupidly ran again w/o checking the VP logs. Now it is running fine for 5 times. So this is an intermittent error. You may want to change the title to remove that it is Z-specific, I think it is a cross-platform issue.

**Comment by bcbrock** [comment]
I caught it again on my system, same crash as Sam:

```
[33m15:20:49.438 [peer] beforeSyncBlocks -> WARN 302[0m Ignoring SyncBlocks message with correlationId = 4, blocks 4964 to 4964, as current correlationId = 6
[33m15:20:49.438 [peer] beforeSyncBlocks -> WARN 303[0m Ignoring SyncBlocks message with correlationId = 4, blocks 4963 to 4963, as current correlationId = 6
[33m15:20:49.438 [peer] beforeSyncBlocks -> WARN 304[0m Ignoring SyncBlocks message with correlationId = 4, blocks 4962 to 4962, as current correlationId = 6
[33m15:20:49.438 [peer] beforeSyncBlocks -> WARN 305[0m Ignoring SyncBlocks message with correlationId = 4, blocks 4961 to 4961, as current correlationId = 6
[33m15:20:50.332 [consensus/obcpbft] weakCheckpointSetOutOfRange -> WARN 306[0m Replica 3 is out of date, f+1 nodes agree checkpoint with seqNo 5410 exists but our high water mark is 5400
[33m15:20:50.385 [consensus/obcpbft] weakCheckpointSetOutOfRange -> WARN 307[0m Replica 3 is out of date, f+1 nodes agree checkpoint with seqNo 5460 exists but our high water mark is 5450
[33m15:20:50.425 [consensus/obcpbft] weakCheckpointSetOutOfRange -> WARN 308[0m Replica 3 is out of date, f+1 nodes agree checkpoint with seqNo 5510 exists but our high water mark is 5500
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x9fb1f7]

goroutine 23 [running]:
panic(0xd1a140, 0xc820010150)
    /usr/src/go/src/runtime/panic.go:464 +0x3e6
github.com/hyperledger/fabric/consensus/obcpbft.(*pbftCore).execDoneSync(0xc8202429a0)
    /gsa/ausgsa/home/b/c/bcbrock/hyperledger/gopath/src/github.com/hyperledger/fabric/consensus/obcpbft/pbft-core.go:902 +0x247
github.com/hyperledger/fabric/consensus/obcpbft.(*pbftCore).main(0xc8202429a0)
    /gsa/ausgsa/home/b/c/bcbrock/hyperledger/gopath/src/github.com/hyperledger/fabric/consensus/obcpbft/pbft-core.go:299 +0x886
created by github.com/hyperledger/fabric/consensus/obcpbft.newPbftCore
    /gsa/ausgsa/home/b/c/bcbrock/hyperledger/gopath/src/github.com/hyperledger/fabric/consensus/obcpbft/pbft-core.go:255 +0x167d
```

**Comment by jyellick** [comment]
@bcbrock @samding01 I think I see what is going on here, I'll try to get this taken care of tomorrow.

**Comment by bmos299** [comment]
@jyellick is there a fix yet for this issue? Do you believe this will allow pbft batch to run successfully?

**Comment by jyellick** [comment]
@bmos299 I have a fix in a PR series I've been working on, let me try to pull it out and submit it alone.

**Comment by bmos299** [comment]
@jyellick thanks.  It would be great if we can add the busywork automation to our bucket for consensus testing.  Obviously, it is exposing some issues.   @bcbrock thanks !

**Comment by jyellick** [comment]
@bmos299 I've submitted the above PR as a very direct solution to the crash.  More sophisticated solutions to prevent racing which might have triggered the condition of the crash are pending.

Definitely agree, +1 to including busywork in our automation, it is a great tool from @bcbrock !

**Comment by samding01** [comment]
After got the latest code commit 07ea01124b2768ee04a6b30fe29a6395f6d3d819, the testing shows the crash is gone but the original problem :  some vp returns a block with "null" is still there. 
Here is the log:

```
# make stress2s
network: ../bin/userModeNetwork -sieve 4
network: Creating a pristine environment
network:     Killing all peer and membersrvc processes
network:     Killing all running and stopped Docker containers
network:     Removing all chaincode containers
network:     Cleaning out BUSYWORK_HOME
network:     Cleaning out /var/hyperledger
network: Running with PBFT Sieve consensus
network: Network Port and PID Map:
network: ------------------------------------------------------------
network:  PeerID |  gRPC  |  REST | Events |  CLI  | Profile |  PID
network: ------------------------------------------------------------
network:     vp0 |  59915 | 54984 |  43616 | 39122 |  57531  | 22881
network:     vp1 |  44602 | 60098 |  50614 | 59727 |  48948  | 22885
network:     vp2 |  46049 | 36330 |  37835 | 56736 |  44794  | 22889
network:     vp3 |  46399 | 60809 |  56187 | 44152 |  42498  | 22901
network: ------------------------------------------------------------
network: Waiting for peers to start
network: Network is up
driver: ./driver -transactions 10000 -peerBurst 100 -interlock -keepLog -checkAgreement -  dupCheck
driver: List of targeted peers with REST API ports
driver:     0.0.0.0:54984
driver:     0.0.0.0:60098
driver:     0.0.0.0:36330
driver:     0.0.0.0:60809
driver: 1 chaincode(s) will be deployed
driver: 1 array(s) will be defined per chaincode
driver: 1 clients will be activated
driver: 10000 transaction(s) will be issued to each array
driver: 10000 total transaction(s) will be issued
driver: busywork::Logger : Logging to /root/.busywork/fabricLog
driver: The log file will persist after exit
driver: Security is disabled
driver: Deploying chaincode(s)
driver: Deployed cc0 as  85f85ecc0fb8a5818c13fd1c073699d77c7c7cee44a772d4abedef5a5f08868df15379ab925fdeba617 618b8e295231636f4a6cbaafdf0819f4f60a143aac927
driver: Waiting up to 5m for chaincode deployments to be registered
driver: Waiting up to 5m for all chaincode containers to be running
driver: Waiting 10s to give chaincode(s) time to initialize
driver: Waiting up to 60s for array creation to be registered
driver: Spawning clients:
driver:     Client 0 is subprocess 26674
driver: Waiting (indefinitely) for subprocesses to complete
fabricLogger:ERROR: 0.0.0.0:36330 @ block 7654: Error getting transactions: missing value to go   with key
fabricLogger:ERROR: Full HTTP token dump
fabricLogger:ERROR: HTTP 'ncode' = '200'
fabricLogger:ERROR:     sock sock2aa662e1800
fabricLogger:ERROR:     http HTTP/1.1 200 OK
fabricLogger:ERROR:     querylength 0
fabricLogger:ERROR:     -queryblocksize 8192
fabricLogger:ERROR:     state body
fabricLogger:ERROR:     charset iso8859-1
fabricLogger:ERROR:     type application/json
fabricLogger:ERROR:     -binary false
fabricLogger:ERROR:     url http://0.0.0.0:36330/chain/blocks/7654
fabricLogger:ERROR:     -keepalive 0
fabricLogger:ERROR:     -timeout 0
fabricLogger:ERROR:     socketinfo 0.0.0.0:36330
fabricLogger:ERROR:     queryoffset 0
fabricLogger:ERROR:     binary 1
fabricLogger:ERROR:     -strict 1
fabricLogger:ERROR:     totalsize 5
fabricLogger:ERROR:     -validate 0
fabricLogger:ERROR:     -protocol 1.1
fabricLogger:ERROR:     connection close
fabricLogger:ERROR:     -queryprogress
fabricLogger:ERROR:     -headers
fabricLogger:ERROR:     -blocksize 8192
fabricLogger:ERROR:     coding
fabricLogger:ERROR:     status ok
fabricLogger:ERROR:     body null

fabricLogger:ERROR:     currentsize 5
fabricLogger:ERROR:     meta Access-Control-Allow-Headers {accept, content-type} Access- Control-Allow-Origin * Content-Type application/json Date {Fri, 27 May 2016 20:21:49 GMT} Content-Length 5 Connection close
fabricLogger:ERROR:     -type application/x-www-form-urlencoded
fabricLogger:ERROR: Aborting
make: *** [stress2s] Error 1
```

and

```
# curl  http://localhost:36330/chain/blocks/7654
 null
```

All 4 peers are running. 
@bcbrock  confirmed that the same error happens on X-86.
