### ISSUE TITLE
panic: runtime error: index out of range encountered when deploying a chaincode

### ISSUE THREAD

**Issue by tribbloid** [hyperledger-archives/fabric#1634]
## Description

 I've encounter a bug:
This is what I do in command line:

```
./peer node start
./peer chaincode deploy -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'

```

then I get the stack trace:

```
15:35:46.812 [main] serve -> INFO 014 Starting peer with id=name:"jdoe" , network id=dev,
address=0.0.0.0:30303, discovery.rootnode=, validator=true
15:35:46.835 [rest] StartOpenchainRESTServer -> INFO 015 Initializing the REST service on 0.0.0.0:5000, TLS is disabled.
panic: runtime error: index out of range
goroutine 28 [running]:
panic(0xd43b20, 0xc8200100d0)
    /opt/go/src/runtime/panic.go:464 +0x3e6
github.com/hyperledger/fabric/core/chaincode/platforms/golang.(*Platform).ValidateSpec(0x15439e8, 0xc82012d4f0, 0x0, 0x0)
    /opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/platforms/golang/platform.go:56 +0x494
github.com/hyperledger/fabric/core.CheckSpec(0xc82012d4f0, 0x0, 0x0)
    /opt/gopath/src/github.com/hyperledger/fabric/core/devops.go:266 +0x261
github.com/hyperledger/fabric/core.(*Devops).getChaincodeBytes(0xc8201a58c0, 0x7f6882509430, 0xc8201fc660, 0xc82012d4f0, 0x100, 0x0, 0x0)
    /opt/gopath/src/github.com/hyperledger/fabric/core/devops.go:93 +0x24d
github.com/hyperledger/fabric/core.(*Devops).Deploy(0xc8201a58c0, 0x7f6882509430, 0xc8201fc660, 0xc82012d4f0, 0x0, 0x0, 0x0)
    /opt/gopath/src/github.com/hyperledger/fabric/core/devops.go:111 +0x78
github.com/hyperledger/fabric/protos._Devops_Deploy_Handler(0xde7b40, 0xc8201a58c0, 0x7f6882509430, 0xc8201fc660, 0xc8201fc750, 0x0, 0x0, 0x0, 0x0)
    /opt/gopath/src/github.com/hyperledger/fabric/protos/devops.pb.go:198 +0x132
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc82020e4e0, 0x7f6882509240, 0xc8201fe750, 0xc820096300, 0xc8201dda40, 0x1504bb0, 0xc8201fc630, 0x0, 0x0)
    /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:350 +0x847
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*Server).handleStream(0xc82020e4e0, 0x7f6882509240, 0xc8201fe750, 0xc820096300, 0xc8201fc630)
    /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:467 +0x743
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*Server).Serve.func2.1.1(0xc82020e4e0, 0x7f6882509240, 0xc8201fe750, 0xc820096300, 0xc8201fc630, 0xc82011ec80)
    /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:278 +0x49
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*Server).Serve.func2.1
    /opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:280 +0x5ac
```
## Describe How to Reproduce

I installed hyperledger-fabric on ubuntu 14.04 on an Amazon web service EC2 m3.medium instance.

By manually running the hotfixed shell script in:

https://github.com/ghaskins/hyperledger-fabric/commit/10cd6f300b40616e0265a684ffe582a83d6322e1

and running ./devenv/setup.sh

both ./peer node start & ./peer node status succeeded with normal status. The above error is triggered when using the ./peer chaincode deploy, which also caused the node to be terminated.

Thanks a lot for any instructions!

**Comment by muralisrini** [comment]
@tribbloid can you let us know commit level of the fabric you are running with ?

**Comment by christo4ferris** [comment]
closing this as there's been no response to @muralisrini question. Please repoen if the problem persists in a more current version, such as v0.5-developer-preview.

**Comment by privoal-ak** [comment]
I encountered this same error as well.
I don't really know why, but GOPATH environment variable was not red correctly at runtime (it was empty) although I could access it in my terminal. It may be a Docker related issue.

I fix it by launching my peer this way : 
GOPATH=$GOPATH ./peer node start

**Comment by privoal-ak** [comment]
My Fabric environment was up to the commit 5cb39849ec2adc3505e523355684eb7370cc85 (august 16th)
