### ISSUE TITLE
Error ocurr when execute behave test

### ISSUE THREAD

**Issue by GrapeBaBa** [hyperledger-archives/fabric#1736]
## Description

when execute 'make behave', error ocurr.

``` shell
cd peer; CGO_CFLAGS=" " CGO_LDFLAGS="-lrocksdb -lstdc++ -lm -lz -lbz2 -lsnappy" go build
Running behave tests
Feature: lanching 3 peers # peer_basic.feature:11
  As a HyperLedger developer
  I want to be able to launch 3 peers
  Scenario: Peers list test, single peer issue #827                            # peer_basic.feature:16
    Given we compose "docker-compose-1.yml"                                    # steps/peer_basic_impl.py:121 0.006s
      Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1456, in run
          match.run(runner.context)
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "steps/peer_basic_impl.py", line 131, in step_impl
          bdd_test_util.cli_call(context, ["docker-compose"] + fileArgsToDockerCompose + ["up","--force-recreate", "-d"], expect_success=True)
        File "/opt/gopath/src/github.com/hyperledger/fabric/bddtests/steps/bdd_test_util.py", line 43, in cli_call
          raise subprocess.CalledProcessError(p.returncode, arg_list, output)
      CalledProcessError: Command '['docker-compose', '-f', u'docker-compose-1.yml', 'up', '--force-recreate', '-d']' returned non-zero exit status 255

      Captured stdout:
      Output:

      Error Message:
      Cannot open self /usr/local/bin/docker-compose or archive /usr/local/bin/docker-compose.pkg

Decomposing with yaml 'docker-compose-1.yml' after scenario Peers list test, single peer issue #827, 
Output:

Error Message:
Cannot open self /usr/local/bin/docker-compose or archive /usr/local/bin/docker-compose.pkg

Exception CalledProcessError: Command '['docker-compose', '-f', u'docker-compose-1.yml', 'kill']' returned non-zero exit status 255
Traceback (most recent call last):
  File "/usr/local/bin/behave", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/behave/__main__.py", line 109, in main
    failed = runner.run()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 672, in run
    return self.run_with_paths()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 693, in run_with_paths
    return self.run_model()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 483, in run_model
    failed = feature.run(self)
  File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 523, in run
    failed = scenario.run(runner)
  File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 919, in run
    runner.run_hook('after_scenario', runner.context, self)
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 405, in run_hook
    self.hooks[name](context, *args)
  File "environment.py", line 40, in after_scenario
    cli_call(context, ["docker-compose"] + fileArgsToDockerCompose + ["kill"], expect_success=True)
  File "/opt/gopath/src/github.com/hyperledger/fabric/bddtests/steps/bdd_test_util.py", line 43, in cli_call
    raise subprocess.CalledProcessError(p.returncode, arg_list, output)
subprocess.CalledProcessError: Command '['docker-compose', '-f', u'docker-compose-1.yml', 'kill']' returned non-zero exit status 255
make: *** [behave] Error 1

```
## Describe How to Reproduce

``` shell
cd $GOPATH/src/github.com/hyperledger/fabric
make behave
```

**Comment by GrapeBaBa** [comment]
reinstall docker-compose it works, it caused by provision failed as china network environment
