### ISSUE TITLE
"Identity or token does not match" even if a correct enrolment ID/secret is used.

### ISSUE THREAD

**Issue by sachikoy** [hyperledger-archives/fabric#1991]
## Description

REST API call to /registrar returns an error  which says "Identity or token does not match" even if a correct enrolment ID/secret is used. 
## Describe How to Reproduce

An easy way to reproduce:
1. set up a blockchain network with multiple (e.g., four) validating peers, with security enabled.
2. access one peer's /registrar as an enrolment ID/secret (e.g., test_user0)
3. access another peer's /registrar using the same enrolment ID/secret (e.g., test_user0)
4. then the second attempt fails with the error mentioned above.

Is this intended by design? A problem is there seems to be no way to allow the user to access to validating peers, or switch from one to another. 
In addition, the same problem seems to occur when a validating peer crashes and rebooted. The enrolment ID that was used before can never be used.

**Comment by angrbrd** [comment]
Hi @sachikoy,

The enrollmentID and enrollmentSecret pair that is used to perform the enrollment with the membership service server is indeed a one-time-use set of credentials. Once you have performed the enrollment one time on one peer, it will fail on subsequent enrollments. This is elaborated on here: 

https://github.com/hyperledger/fabric/blob/master/docs/API/SandboxSetup.md#note-on-security-functionality

If you must you send your transaction to one of the other peer IP addresses, not the original peer IP that performed the user enrollment, that second peer will not have the appropriate user cert/tokens to transact. The current approach to transacting through multiple peers was to configure the application and peer nodes to replicate the location of the stored crypto among themselves. This was the approach that was discussed quite some time ago. @adecaro and @elli-androulaki, I assume that is still the suggested approach at this time? 

Though I appreciate you bringing this issue back up to our attention as we need to document a more straight forward way of actually going through the procedure above.

**Comment by sachikoy** [comment]
Hi @angrbrd 
So I think the current design assumes that when a user performed enrolment on one peer, the peer is trusted by the user, and maintains the security tokens (especially the private key of Ecert) for the user, retrieve Tcerts and sign transaction using the Tcert keys.
But on the other hand, when one access the REST API, he can easily impersonate another user by specifying the enrolment ID in the REST request.
I raised the issue before. https://github.com/hyperledger/fabric/issues/1459

I still cannot understand what is the best practice for using the REST API with security.

**Comment by smithbk** [comment]
@sachikoy The REST API is not secure.  You should use the new node SDK API.  This will keep the ecert's private key in the local KeyValStore, which means it doesn't matter which peer you connect to.  See fabric/sdk/node/README.md for more info.

**Comment by kishansag** [comment]
`
kishan@kishan-Inspiron-3542:~/composer-sample-app/scripts$ rm -rf node_modules && npm cache clean && npm install



> composer-sample-app@0.0.1 preinstall /home/kishan/composer-sample-app

> composer --version || { echo 'Please first run npm install -g composer-cli'; exit 1;} 





composer-cli                   v0.7.2

composer-admin                 v0.7.2

composer-client                v0.7.2

composer-common                v0.7.2

composer-runtime-hlf           v0.7.2





> composer-sample-app@0.0.1 install /home/kishan/composer-sample-app

> scripts/download-hyperledger.sh && scripts/start-hyperledger.sh && npm run deployNetwork





# Grab the current directory.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

 cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd 

 dirname "${BASH_SOURCE[0]}" 



# Shut down the Docker containers that might be currently running.

cd "${DIR}"/scripts

docker-compose kill && docker-compose down

Killing scripts_membersrvc_1 ... done

Removing scripts_vp0_1 ... done

Removing scripts_membersrvc_1 ... done



# TODO change this to alter the default profile which is, by convention, a local running hyperledger fabric

rm -rf ~/.composer-connection-profiles/defaultProfile/*

rm -rf ~/.composer-credentials/*





# delete all existing containers and images

# This is not used in general usage but this might

#read -p "Press y to delete all docker containers images" -n 1 -r

#echo    # (optional) move to a new line

#if [[ $REPLY =~ ^[Yy]$ ]]

#then

#  docker rm $(docker ps -a -q) -f

#  docker rmi $(docker images -q) -f

#fi



# Pull and tag the latest Hyperledger Fabric base image.

docker pull hyperledger/fabric-baseimage:x86_64-0.1.0

x86_64-0.1.0: Pulling from hyperledger/fabric-baseimage

Digest: sha256:ac6a2784cfd028ae62f5688f4436f95d7a60eeacd8506eb303c9c6335328c388

Status: Image is up to date for hyperledger/fabric-baseimage:x86_64-0.1.0

docker tag hyperledger/fabric-baseimage:x86_64-0.1.0 hyperledger/fabric-baseimage:latest



# Grab the current directorydirectory.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

 cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd 

 dirname "${BASH_SOURCE[0]}" 



#

cd "${DIR}"/scripts



# Start up the Hyperledger Fabric

docker-compose up -d --build

Creating scripts_membersrvc_1 ... 

Creating scripts_membersrvc_1 ... done

Creating scripts_vp0_1 ... 

Creating scripts_vp0_1 ... done





# Wait for the Hyperledger Fabric to start.

while ! nc localhost 7051 </dev/null; do sleep 1; done

while ! nc localhost 7053 </dev/null; do sleep 1; done

while ! nc localhost 7054 </dev/null; do sleep 1; done

sleep 5



> composer-sample-app@0.0.1 deployNetwork /home/kishan/composer-sample-app

> composer archive create --archiveFile digitalproperty-network.bna --sourceType module --sourceName digitalproperty-network && composer network deploy --archiveFile  digitalproperty-network.bna  --enrollId admin --enrollSecret Xurw3yU9zI0l 





Creating Business Network Archive



Node module search path : 

undefined 



Not found in main node_module search path, trying current directory :/home/kishan/composer-sample-app/node_modules/digitalproperty-network

Looking for package.json of Business Network Definition in /home/kishan/composer-sample-app/node_modules/digitalproperty-network



Found:

Description:Digital Property Network

Name:digitalproperty-network

Identifier:digitalproperty-network@0.0.7



Written Business Network Definition Archive file to digitalproperty-network.bna

Command completed successfully.



Command succeeded





Deploying business network from archive: digitalproperty-network.bna

Business network definition:

	Identifier: digitalproperty-network@0.0.7

	Description: Digital Property Network



events.js:160

      throw er; // Unhandled 'error' event

      ^



Error

    at ClientDuplexStream._emitStatusIfDone (/home/kishan/.nvm/versions/node/v6.10.3/lib/node_modules/composer-cli/node_modules/grpc/src/node/src/client.js:189:19)

    at ClientDuplexStream._readsDone (/home/kishan/.nvm/versions/node/v6.10.3/lib/node_modules/composer-cli/node_modules/grpc/src/node/src/client.js:158:8)

    at readCallback (/home/kishan/.nvm/versions/node/v6.10.3/lib/node_modules/composer-cli/node_modules/grpc/src/node/src/client.js:217:12)

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! composer-sample-app@0.0.1 deployNetwork: `composer archive create --archiveFile digitalproperty-network.bna --sourceType module --sourceName digitalproperty-network && composer network deploy --archiveFile  digitalproperty-network.bna  --enrollId admin --enrollSecret Xurw3yU9zI0l `

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the composer-sample-app@0.0.1 deployNetwork script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



npm ERR! A complete log of this run can be found in:

npm ERR!     /home/kishan/.npm/_logs/2017-05-23T09_10_01_446Z-debug.log

npm WARN composer-sample-app@0.0.1 No repository field.

npm WARN composer-sample-app@0.0.1 license should be a valid SPDX license expression

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! composer-sample-app@0.0.1 install: `scripts/download-hyperledger.sh && scripts/start-hyperledger.sh && npm run deployNetwork`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the composer-sample-app@0.0.1 install script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



npm ERR! A complete log of this run can be found in:

npm ERR!     /home/kishan/.npm/_logs/2017-05-23T09_10_01_589Z-debug.log
`

**Comment by kishansagathiya** [comment]
@angrbrd @sachikoy 
I am also getting the same error(dentity or token does not match) even though I am using correct enrollID and enrollSecret. I have gone through all the discussion here and also https://github.com/hyperledger-archives/fabric/issues/2004, but I am not able to figure out how to rectify this.

Below is the command that is causing the error 
```
kishan@kishan-Inspiron-3542:~/composer-sample-app$ composer archive create --archiveFile digitalproperty-network.bna --sourceType module --sourceName digitalproperty-network && composer network deploy --archiveFile  digitalproperty-network.bna  --enrollId admin --enrollSecret Xurw3yU9zI0l

Creating Business Network Archive

Node module search path : 
undefined 

Not found in main node_module search path, trying current directory :/home/kishan/composer-sample-app/node_modules/digitalproperty-network
Looking for package.json of Business Network Definition in /home/kishan/composer-sample-app/node_modules/digitalproperty-network

Found:
Description:Digital Property Network
Name:digitalproperty-network
Identifier:digitalproperty-network@0.0.7

Written Business Network Definition Archive file to digitalproperty-network.bna
Command completed successfully.

Command succeeded


Deploying business network from archive: digitalproperty-network.bna
Business network definition:
	Identifier: digitalproperty-network@0.0.7
	Description: Digital Property Network


Error: Identity or token does not match.
Command failed

kishan@kishan-Inspiron-3542:~/composer-sample-app$ 
```
Also @angrbrd https://github.com/hyperledger/fabric/blob/master/docs/API/SandboxSetup.md#note-on-security-functionality link does not exist if there is some other link where this material is available, plz post the link here.
