### ISSUE TITLE
Latest commit fails car_test.go on zLinux

### ISSUE THREAD

**Issue by gongsu832** [hyperledger-archives/fabric#2035]
## Description

commit ce66cb6673963abf21b3de6b2f49c1ac25c4fb1c
Merge: 586376c 696f265
Author: Sheehan Anderson sranderson@gmail.com
Date:   Mon Jun 27 17:35:31 2016 -0400

```
Merge pull request #2008 from jyellick/clear-batch-on-viewchange-master

Clear batch store on view change
```

The test used to be done only within vagrant. I guess support was added for x86 to do the test outside vagrant so commit f9323ab9cafa74e9b9133d00799046878827a0d5 removed the vagrant check. But the base image for s390x hyperledger/fabric-baseimage:s390x-0.0.10 hasn't been updated to support it.

```
2016/06/27 18:03:41 Load docker HostConfig: &{Binds:[] CapAdd:[] CapDrop:[] ContainerIDFile: LxcConf:[] Privileged:false PortBindings:map[] Links:[] PublishAllPorts:false DNS:[] DNSSearch:[] ExtraHosts:[] VolumesFrom:[] NetworkMode:host IpcMode: PidMode: UTSMode: RestartPolicy:{Name: MaximumRetryCount:0} Devices:[] LogConfig:{Type: Config:map[]} ReadonlyRootfs:false SecurityOpt:[] CgroupParent: Memory:0 MemorySwap:0 MemorySwappiness:0 OOMKillDisable:false CPUShares:0 CPUSet: CPUSetCPUs: CPUSetMEMs: CPUQuota:0 CPUPeriod:0 BlkioWeight:0 Ulimits:[]}
2016/06/27 18:03:41 setting Number of procs to -1, was 2
2016/06/27 18:03:57 Failed Chaincode docker build:
Step 1 : FROM hyperledger/fabric-ccenv
 ---> 7f70470ce8f5
Step 2 : COPY package.car /tmp/package.car
 ---> 89b1008fba9e
Removing intermediate container e45aa0c3318e
Step 3 : RUN chaintool buildcar /tmp/package.car -o $GOPATH/bin/59e6d86af71e71bf54d25247d019c08733fa9897496a00edcf0c0d1779e8814b83418da68410b989a0311d6f008812b98f0b6283b5221674385443ba582ed16d && rm /tmp/package.car
 ---> Running in 49dcc957ecee
OpenJDK 64-Bit Zero VM warning: TieredCompilation is disabled in this release.
Building CAR /tmp/package.car
[CCI] parse org.hyperledger.chaincode.example02.cci
[CCI] parse appinit.cci
[PB] protoc --go_out=/tmp/buildcar-1467065035773-2999101557/build/src/hyperledger/cci/org/hyperledger/chaincode/example02 --proto_path=/tmp/buildcar-1467065035773-2999101557/build/src/hyperledger/cci/org/hyperledger/chaincode/example02 /tmp/buildcar-1467065035773-2999101557/build/src/hyperledger/cci/org/hyperledger/chaincode/example02/interface.proto
Exception in thread "main" java.io.IOException: Cannot run program "protoc": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at me.raynes.conch.low_level$proc.invokeStatic(low_level.clj:33)
    at me.raynes.conch.low_level$proc.doInvoke(low_level.clj:7)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invokeStatic(core.clj:648)
    at clojure.core$apply.invoke(core.clj:641)
    at me.raynes.conch$run_command.invokeStatic(conch.clj:197)
    at me.raynes.conch$run_command.invoke(conch.clj:196)
    at me.raynes.conch$execute.invokeStatic(conch.clj:245)
    at me.raynes.conch$execute.doInvoke(conch.clj:236)
    at clojure.lang.RestFn.applyTo(RestFn.java:139)
    at clojure.core$apply.invokeStatic(core.clj:648)
    at clojure.core$apply.invoke(core.clj:641)
    at chaintool.build.golang$protoc.invokeStatic(golang.clj:31)
    at chaintool.build.golang$protoc.doInvoke(golang.clj:31)
    at clojure.lang.RestFn.invoke(RestFn.java:457)
    at chaintool.build.golang$protoc_cmd.invokeStatic(golang.clj:71)
    at chaintool.build.golang$protoc_cmd.invoke(golang.clj:64)
    at chaintool.build.golang$emit_proto.invokeStatic(golang.clj:167)
    at chaintool.build.golang$emit_proto.invoke(golang.clj:159)
    at chaintool.build.golang$compile$iter__2096__2100$fn__2101.invoke(golang.clj:180)
    at clojure.lang.LazySeq.sval(LazySeq.java:40)
    at clojure.lang.LazySeq.seq(LazySeq.java:49)
    at clojure.lang.RT.seq(RT.java:521)
    at clojure.core$seq__4357.invokeStatic(core.clj:137)
    at clojure.core$dorun.invokeStatic(core.clj:3024)
    at clojure.core$dorun.invoke(core.clj:3024)
    at chaintool.build.golang$compile.invokeStatic(golang.clj:179)
    at chaintool.build.golang$compile.invoke(golang.clj:173)
    at chaintool.build.core$compile.invokeStatic(core.clj:27)
    at chaintool.build.core$compile.invoke(core.clj:22)
    at chaintool.subcommands.buildcar$run.invokeStatic(buildcar.clj:41)
    at chaintool.subcommands.buildcar$run.invoke(buildcar.clj:32)
    at chaintool.core$_app.invokeStatic(core.clj:151)
    at chaintool.core$_app.doInvoke(core.clj:119)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invokeStatic(core.clj:646)
    at clojure.core$apply.invoke(core.clj:641)
    at chaintool.core$_main.invokeStatic(core.clj:160)
    at chaintool.core$_main.doInvoke(core.clj:159)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at chaintool.core.main(Unknown Source)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 41 more

--- FAIL: TestCar_BuildImage (15.35s)
    car_test.go:52: Error building Chaincode container: Error building Chaincode container: The command '/bin/sh -c chaintool buildcar /tmp/package.car -o $GOPATH/bin/59e6d86af71e71bf54d25247d019c08733fa9897496a00edcf0c0d1779e8814b83418da68410b989a0311d6f008812b98f0b6283b5221674385443ba582ed16d && rm /tmp/package.car' returned a non-zero code: 1
FAIL
coverage: 0.0% of statements
FAIL    github.com/hyperledger/fabric/core/chaincode/platforms/car/test 15.361s
```
## Describe How to Reproduce

make unit-test

**Comment by rameshthoomu** [comment]
Observed same error in Jenkins Z builds.. Below is the reference log: Z builds are failing

https://jenkins.hyperledger.org/job/fabric-github-verify-z/351/console

**Comment by s390xlinux** [comment]
This is due to the hyperledger/fabric-baseimage:s390x-0.0.10 not having protoc installed because that also requires a patch to compile on s390x. I've given the patch to Volodymyr Paprotski/Toronto/IBM who worked with Greg Haskins to create that image. I don't know when they will update the image to include protoc.

**Comment by rameshthoomu** [comment]
@vpaprots : Any update on the package given by @s390xlinux?

**Comment by vpaprots** [comment]
@s390xlinux Gong, please create a pull request based on the changes you would like to see in https://github.com/hyperledger/fabric/blob/master/images/base/scripts/common/setup.sh#L106

@ghaskins Greg has commit priviledges and can review your pull request. Greg, do you think we will need a new baseimage version to fix protoc on 390?

Once setup.sh is updated, re-uploading baseimage:0.0.10 or uploading new version of baseimage:0.0.11 can be handled asynchronously.

**Comment by rameshthoomu** [comment]
Above said issue is occurring only in fabric master branch.

**Comment by s390xlinux** [comment]
Pull request for setup.sh using gongsu832/protobuf to build s390x baseimage has been submitted.

https://github.com/hyperledger/fabric/pull/2083
