### ISSUE TITLE
makedoc.sh yields error

### ISSUE THREAD

**Issue by christo4ferris** [hyperledger-archives/fabric#2198]
## Description

Running makedoc.sh to generate the node sdk docs yields following error.

```
fs.js:844
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat '/Users/cbf/dev/gocode/src/github.com/hyperledger/fabric/sdk/node/typings/globals/node/index.d.ts'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at /usr/local/lib/node_modules/typedoc/lib/application.js:130:20
    at Array.forEach (native)
    at CliApplication.Application.expandInputFiles (/usr/local/lib/node_modules/typedoc/lib/application.js:128:20)
    at CliApplication.bootstrap (/usr/local/lib/node_modules/typedoc/lib/cli.js:52:28)
    at CliApplication.Application (/usr/local/lib/node_modules/typedoc/lib/application.js:33:14)
    at new CliApplication (/usr/local/lib/node_modules/typedoc/lib/cli.js:29:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/typedoc/bin/typedoc:4:1)
    at Module._compile (module.js:409:26)
```
## Describe How to Reproduce

running MacOSX El Capitan
install 'typings' then run makedoc.sh

```
cd $GOPATH/src/github.com/hyperledger/fabric/sdk/node
npm install -g typings
./makedoc.sh
```

**Comment by bryan-huangyan** [comment]
@christo4ferris you should run **typings install**, before run makedoc.sh

**Comment by christo4ferris** [comment]
ah, I see it now in the Makefile.
