### ISSUE TITLE
invokes do not go thru with large payload (1M)

### ISSUE THREAD

**Issue by dongmingh** [hyperledger-archives/fabric#2262]
## Description

commit level: **3e0e80a898b259fe463295eabff80ee64f20695e**
branch: **v0.5-developer-preview**

When test invokes (200 transactions with 1 thread) with large payload, about 1.3M, only part of transactions recorded to ledger. Only 68 out of 200 transactions are recorded in LPAR Z and 10 out of 200 were recorded on local Lenovo W540.
Once this occurs, no more invoke will be recorded.
## Describe How to Reproduce
1. Launch a 4-peer network, pbft-batch, security and privacy enabled
2. login and deploy chaincode:
   https://github.com/ratnakar-asara/artchaincode
   `peer chaincode deploy -l golang -n mycc -c '{"Function": "init", "Args":["INITIALIZE"]}'`
3. invoke PostUser 
   `peer chaincode invoke -l golang -n mycc -c '{"Function": "PostUser", "Args":["100", "USER", "Ashley   Hart", "TRD",  "Morrisville Parkway, #216, Morrisville, NC 27560", "9198063535", "ashley@itpeople.com", "SUNTRUST", "0001732345", "0234678"]}'`
4. invoke "PostItem"
    `peer chaincode invoke -l golang -n mycc -c '{"Function": "PostItem", "Args":["1000", "ARTINV", "Shadows by Asppen", "Asppen Messer", "20140202", "Original", "landscape", "Canvas", "15 x 15 in", "art1.png","600", "100"]}'`
5. invoke 200 times for PostItem
6. check block number, only part of transactions got recorded into ledger.

**Comment by tuand27613** [comment]
do you have peer and chaincode logs ?

**Comment by ratnakar-asara** [comment]
Here Invoke with function **PostItem** will create the binary data (about 1.3 MB) from the input argument art1.png and inserts that data in to the tables, Invoke request's aren't received to chaincode.

**Comment by dongmingh** [comment]
@tuand27613 when the issue occurred, the log level was set to error.  We recreated it again with log level set to debug, but the log was so large that the system almost stops.  So we deleted the logs.  However, this issue is easy to recreate.  I was able to recreate it on my local system.  Moreover, we do not know where it broke.  Any particular log level setting you suggest for recreation?

**Comment by tuand27613** [comment]
let's start with log_level=error  .  And turn chaincode logging on as well.

**Comment by tuand27613** [comment]
also, what are you using as the client ?  soapUI or behave ? can we have a behave test that we can use to reproduce ?

**Comment by dongmingh** [comment]
The issue was seen when using either SoapUI or jmeter.
Here is the recreation log (only from vp0, the others are too big to upload), `http://chunk.io/f/511af4fc943445cf889571ad5f8376e1`
Let us know if you need others, we will find a way to pass to you.
This is recreated on local system W540 using SoapUI. Only 44 of 200 transactions are recorded into ledger.  We notice that peers 1, 2, 3 are down.

**Comment by tuand27613** [comment]
The vp0 shows that it's executing seqNo=18, i.e. the 17th invoke request with deploy being request 1. 
No error. No view-change. Log just stops recording on "add DataNode" from [buckettree].

Can you post the last page or so of the vp1/2/3 logs, perhaps we can see how they stopped ?

**Comment by dongmingh** [comment]
The end of vp1 and vp 3 logs contain binary characters.
The end of vp2 log shows panic:
15:14:02.236 [peer] HandleMessage -> DEBU 44b2 Handling Message of type: DISC_GET_PEERS
15:14:02.236 [peer] beforeGetPeers -> DEBU 44b3 Sending back DISC_PEERS
15:14:02.236 [peer] SendMessage -> DEBU 44b4 Sending message to stream of type: DISC_PEERS
15:14:02.249 [peer] SendMessage -> DEBU 44b5 Sending message to stream of type: DISC_GET_PEERS
15:14:02.250 [consensus/handler] HandleMessage -> DEBU 44b6 Did not handle message of type DISC_PEERS, passing on to next MessageHandler
15:14:02.250 [peer] HandleMessage -> DEBU 44b7 Handling Message of type: DISC_PEERS
15:14:02.250 [peer] beforePeers -> DEBU 44b8 Received DISC_PEERS, grabbing peers message
15:14:02.250 [peer] beforePeers -> DEBU 44b9 Received PeersMessage with Peers: peers:<ID:<name:"vp3" > address:"172.17.0.6:30303" type:VALIDATOR pkiID:"\357j\246Yv\367\343\007_]4+`xuW\361\331\310\342\256\343O\323\347m\3532\376\307]\317" > peers:<ID:<name:"vp0" > address:"172.17.0.1:30001" type:VALIDATOR pkiID:"0\201\274\006\213\254\315\202\025\204\263\320\037\"\256\321\366\":U\014\321\215\004\301\376\345\217v\022\331\246" > peers:<ID:<name:"vp2" > address:"172.17.0.5:30303" type:VALIDATOR pkiID:"\016\345\nq!\255A\020p\347\n\324\244e\277\301\374%\026\213i\276\237\030\270\276yR\277\250\306J" >
15:14:02.256 [peer] SendMessage -> DEBU 44ba Sending message to stream of type: DISC_GET_PEERS
panic: State can be changed only in context of a tx.
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x63d457]

goroutine 384 [running]:
panic(0xd56340, 0xc8200120b0)
        /opt/go/src/runtime/panic.go:464 +0x3e6
github.com/hyperledger/fabric/core/chaincode.(_Handler).enterBusyState.func1.1(0xc8253f5f80, 0xc820402140, 0xc8202c9be8)
        /opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/handler.go:1010 +0x307
panic(0xbe0a00, 0xc8202e8000)
        /opt/go/src/runtime/panic.go:426 +0x4e9
github.com/hyperledger/fabric/core/ledger/statemgmt/state.(_State).Set(0xc820354eb0, 0xc8253ff500, 0x80, 0xc8202e9000, 0xf, 0xc821f3a000, 0x14d1d7, 0x14e000, 0x0, 0x0)
        /opt/gopath/src/github.com/hyperledger/fabric/core/ledger/statemgmt/state/state.go:143 +0x2bd
github.com/hyperledger/fabric/core/ledger.(_Ledger).SetState(0xc82039af80, 0xc8253ff500, 0x80, 0xc8202e9000, 0xf, 0xc821f3a000, 0x14d1d7, 0x14e000, 0x0, 0x0)
        /opt/gopath/src/github.com/hyperledger/fabric/core/ledger/ledger.go:247 +0xad
github.com/hyperledger/fabric/core/chaincode.(_Handler).enterBusyState.func1(0xc8204ac0e0, 0xc8253f5f80, 0xe83990, 0x8)
        /opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/handler.go:1041 +0x1436
created by github.com/hyperledger/fabric/core/chaincode.(*Handler).enterBusyState
        /opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/handler.go:1107 +0x53

**Comment by muralisrini** [comment]
With large payload with privacy on, processing takes longer time. I think the invoke transaction bails out with timeout error (timeout was set to 1 sec).  When ledger.SetState kicks in later it raises the _State can be changed only in context of a tx._ panic. 

Requested @dongmingh to run with a larger timeout to verify this theory.

**Comment by dongmingh** [comment]
per @muralisrini suggested, set the chaincode timeout from 1s to 30s for test and do not see the panic issue.  However, learned that the chain height can only reach 21 on my Lenovo W540.  Before the chain heoght reaches 21, all transactions are recorded normally.  Once the height reaches 21, no more transactions can be recorded and the height remains 21, see bug #2292.
