### ISSUE TITLE
sdk/node:  newChain(42) breaks registrar.js test

### ISSUE THREAD

**Issue by jjjjibm** [hyperledger-archives/fabric#2294]
## Description

HFC version 0.0.2
# This error occurs while running make node-sdk-unit-tests:

 enroll again
enrollAgain
enrollAgain: calling newChain(42)
enrollAgain: back from newChain()
/opt/gopath/src/github.com/hyperledger/fabric/sdk/node/test/unit/registrar.js:134
   chain.setKeyValStore(hfc.newFileKeyValStore('/tmp/keyValStore'));
   ^
ReferenceError: chain is not defined
    at enrollAgain (/opt/gopath/src/github.com/hyperledger/fabric/sdk/node/test/unit/registrar.js:134:4)
    at Test.<anonymous> (/opt/gopath/src/github.com/hyperledger/fabric/sdk/node/test/unit/registrar.js:48:5)
    at Test.bound [as _cb](/opt/gopath/src/github.com/hyperledger/fabric/sdk/node/node_modules/tape/lib/test.js:63:32)
    at Test.run (/opt/gopath/src/github.com/hyperledger/fabric/sdk/node/node_modules/tape/lib/test.js:82:10)
    at Test.bound [as run](/opt/gopath/src/github.com/hyperledger/fabric/sdk/node/node_modules/tape/lib/test.js:63:32)
    at Immediate.next [as _onImmediate](/opt/gopath/src/github.com/hyperledger/fabric/sdk/node/node_modules/tape/lib/results.js:70:15)
    at processImmediate [as _immediateCallback](timers.js:367:17)
ERROR running registrar tests!
END running registrar tests

Here is the documentation for getChain() function:

newChain

```
newChain(name: **any**): any

    Defined in src/hfc.ts:2669

Create a new chain. If it already exists, throws an Error.
Parameters
    name: **any**

    Name of the chain. It can be any name and has value only for the client.
Returns any
```

I reckoned 'name:any' means any value, so I tried value 42 and got this error. 
## Describe How to Reproduce

1.make node-sdk-unit-tests to establish baseline success
2.Edit sdk/node/test/unit/registrar.js, function enrollAgain(cb)
3.Change hfc.newChain("testChain2") to hfc.newChain(42) 

For example,
/var chain = hfc.newChain("testChain2");
   //var chain = hfc.newChain("");
     var chain2 = hfc.newChain(42)

4.Save registrar.js
5.make node-sdk-unit-tests

**Comment by christo4ferris** [comment]
@jjjjibm please migrate to Jira. Thanks

**Comment by jjjjibm** [comment]
The Jira issue for this problem is FAB-127
