### ISSUE TITLE
hfc.getChain(<brand new name>, create=yes) fails with ReferenceError: name is not defined

### ISSUE THREAD

**Issue by jjjjibm** [hyperledger-archives/fabric#2342]
My program calls hfc.getChain with a new chain name and the create flag.  
GetChain calls hfc.newChain() because the chain has not been allocated yet. 

The call fails like this: 
_setChainFields: calling getChain()    <--- message from my program_ 

The rest is from node.js: 
/_opt/gopath/src/github.com/hyperledger/fabric/sdk/node/lib/hfc.js:2194
        chain = newChain(name);
                         ^
**ReferenceError: name is not defined**
    at Object.getChain (/opt/gopath/src/github.com/hyperledger/fabric/sdk/node/lib/hfc.js:2194:26)
    at setChainFields (/opt/gopath/src/github.com/hyperledger/fabric/sdk/node/test/unit/registrar2.js:88:18)
    at Test.<anonymous> (/opt/gopath/src/github.com/hyperledger/fabric/sdk/node/test/unit/registrar2.js:65:5)
    at Test.bound [as _cb](/opt/gopath/src/github.com/hyperledger/fabric/sdk/node/node_modules/tape/lib/test.js:63:32)
    at Test.run (/opt/gopath/src/github.com/hyperledger/fabric/sdk/node/node_modules/tape/lib/test.js:82:10)
    at Test.bound [as run](/opt/gopath/src/github.com/hyperledger/fabric/sdk/node/node_modules/tape/lib/test.js:63:32)
    at Immediate.next [as _onImmediate](/opt/gopath/src/github.com/hyperledger/fabric/sdk/node/node_modules/tape/lib/results.js:70:15)
    at processImmediate [as _immediateCallback](timers.js:367:17)_

Looking at the getChain function in hfc.ts

export function getChain(**chainName**, create) {
    let chain = _chains[**chainName**];
    if (!chain && create) {
        chain = newChain(**name**);
    }
    return chain;
}: 

we notice getChain() takes the parameter chainName and looks up chainName, but when it creates a new chain, it passes a new variable, name.  Could it be newChain should have been called like this?
   chain = newChain(chainName) 
## Describe How to Reproduce

Add this to register.js or to a similar program: 
 **var  create = true; 
  var chain = hfc.getChain("testChain3", create);**

where "testChain3"  has not been allocated yet.

**Comment by christo4ferris** [comment]
@jjjjibm we've migrated to using [Jira](https://jira.hyperledger.org/secure/RapidBoard.jspa?projectKey=FAB&rapidView=7&view=planning) for issue tracking, if you think this issue should be re-opened, please open an issue there. You'll need a [Linux Foundation ID](https://identity.linuxfoundation.org/) to login. 
Thanks

**Comment by jjjjibm** [comment]
The Jira issue corresponding to this test is FAB-128
