### ISSUE TITLE
panic: Our blockchain is already higher than a sync target, this is unlikely, but unimplemented

### ISSUE THREAD

**Issue by dongmingh** [hyperledger-archives/fabric#2343]
## Description

On LPAR Z system 4-peer pbft-batch, security and privacy enabled
execute ART chaincode with about 1K payload, peer 3 crashes with the message:

panic: Our blockchain is already higher than a sync target, this is unlikely, but unimplemented

goroutine 45 [running]:
panic(0x2aa356b7280, 0xc826264ec0)
        /opt/hyperledger/go/src/runtime/panic.go:481 +0x400
github.com/hyperledger/fabric/core/peer/statetransfer.(_coordinatorImpl).syncBlockchainToCheckpoint(0xc8202f6420, 0xc82131c460)
        /opt/hyperledger/git/src/github.com/hyperledger/fabric/core/peer/statetransfer/statetransfer.go:452 +0x24a
github.com/hyperledger/fabric/core/peer/statetransfer.(_coordinatorImpl).blockThread(0xc8202f6420)
        /opt/hyperledger/git/src/github.com/hyperledger/fabric/core/peer/statetransfer/statetransfer.go:605 +0x4a0
created by github.com/hyperledger/fabric/core/peer/statetransfer.(*coordinatorImpl).Start
        /opt/hyperledger/git/src/github.com/hyperledger/fabric/core/peer/statetransfer/statetransfer.go:132 +0x3c
## Describe How to Reproduce

Login to Z
1. deploy chaincode, https://github.com/ratnakar-asara/artchaincode
2. execute invokes with 100 threads
3. peer 3 crashes about 7 min late

I will post the log if needed.

**Comment by tuand27613** [comment]
post logs for all peers. Thanks !

**Comment by dongmingh** [comment]
All logs are handled over to @tuand27613 this afternoon.

**Comment by christo4ferris** [comment]
@dongmingh we've migrated to using [Jira](https://jira.hyperledger.org/secure/RapidBoard.jspa?projectKey=FAB&rapidView=7&view=planning) for issue tracking, if you think this issue should be re-opened, please open an issue there. You'll need a [Linux Foundation ID](https://identity.linuxfoundation.org/) to login. 
Thanks
