### ISSUE TITLE
panic: Test network took more than 60 seconds to resolve requests, this usually indicates a hang

### ISSUE THREAD

**Issue by rameshthoomu** [hyperledger-archives/fabric#2345]
## Description

Observed panic error in one of the jenkins build while running unit-tests. Not always reproducing.. 

```
--- FAIL: TestClassicBackToBackStateTransfer (60.17s)
00:09:35.222 panic: Test network took more than 60 seconds to resolve requests, this usually indicates a hang [recovered]
00:09:35.222    panic: Test network took more than 60 seconds to resolve requests, this usually indicates a hang
00:09:35.222 
00:09:35.222 goroutine 226 [running]:
00:09:35.222 panic(0xaa4160, 0xc820580960)
00:09:35.222    /opt/go/go1.6.linux.amd64/src/runtime/panic.go:464 +0x3e6
00:09:35.222 testing.tRunner.func1(0xc8203685a0)
00:09:35.222    /opt/go/go1.6.linux.amd64/src/testing/testing.go:467 +0x192
00:09:35.222 panic(0xaa4160, 0xc820580960)
00:09:35.222    /opt/go/go1.6.linux.amd64/src/runtime/panic.go:426 +0x4e9
00:09:35.222 github.com/hyperledger/fabric/consensus/pbft.(*testnet).process(0xc820316040, 0x0, 0x0)
00:09:35.222    /w/workspace/fabric-verify-x86_64/gopath/src/github.com/hyperledger/fabric/consensus/pbft/mock_network_test.go:230 +0x33e
00:09:35.222 github.com/hyperledger/fabric/consensus/pbft.TestClassicBackToBackStateTransfer(0xc8203685a0)
00:09:35.222    /w/workspace/fabric-verify-x86_64/gopath/src/github.com/hyperledger/fabric/consensus/pbft/batch_test.go:334 +0x3c3
00:09:35.222 testing.tRunner(0xc8203685a0, 0x1303bd0)
00:09:35.222    /opt/go/go1.6.linux.amd64/src/testing/testing.go:473 +0x98
00:09:35.222 created by testing.RunTests
00:09:35.222    /opt/go/go1.6.linux.amd64/src/testing/testing.go:582 +0x892
00:09:35.222 FAIL   github.com/hyperledger/fabric/consensus/pbft    61.923s
```
## Describe How to Reproduce

Jenkins build reference:
https://jenkins.hyperledger.org/view/fabric/job/fabric-verify-x86_64/74/consoleFull

**Comment by rameshthoomu** [comment]
Closing this issue as this is tracking in JIRA.
