### ISSUE TITLE
TestServer_Chat test case in peer_test.go.go fails

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#256]
The test case TestServer_Chat in peer_test.go fails with the following error

```
chainlet env using [startuptimeout-20000, chaincode run mode-net_mode, peer address-0.0.0.0:30303]
2015/11/18 17:16:03 setting Number of procs to 2, was 2
2015/11/18 17:16:03 transport: http2Client.notifyError got notified that the client transport was broken EOF.
--- FAIL: TestServer_Chat (0.03s)
    peer_test.go:76: Received message: DISC_HELLO
    peer_test.go:72: stream closed with unexpected error: rpc error: code = 13 desc = "transport is closing"
FAIL
FAIL    github.com/openblockchain/obc-peer/openchain/peer   0.070s
```

The peer exits with the following error

```
17:16:03.853 [peer] beforeHello -> DEBU 00a Received DISC_HELLO from endpoint=
17:16:03.854 [peer] beforeHello -> DEBU 00c Received DISC_HELLO, sending back DISC_HELLO
panic: runtime error: invalid memory address or nil pointer dereference
    panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5645d7]

goroutine 24 [running]:
github.com/openblockchain/obc-peer/openchain/peer.getHandlerKey(0x7ff581cb3128, 0xc820061c00, 0x0, 0x0, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/peer/peer.go:209 +0x1d7
github.com/openblockchain/obc-peer/openchain/peer.(*Peer).DeregisterHandler(0xc8201d6f90, 0x7ff581cb3128, 0xc820061c00, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/peer/peer.go:235 +0x4f
github.com/openblockchain/obc-peer/openchain/peer.(*Handler).Stop(0xc820061c00, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/peer/handler.go:101 +0x97
github.com/openblockchain/obc-peer/openchain/peer.getHandlerKey(0x7ff581cb3128, 0xc820061c00, 0x0, 0x0, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/peer/peer.go:209 +0x1d7
github.com/openblockchain/obc-peer/openchain/peer.(*Peer).RegisterHandler(0xc8201d6f90, 0x7ff581cb3128, 0xc820061c00, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/peer/peer.go:218 +0x4f
github.com/openblockchain/obc-peer/openchain/peer.(*Handler).beforeHello(0xc820061c00, 0xc8200bd650)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/peer/handler.go:147 +0x106e
github.com/openblockchain/obc-peer/openchain/peer.NewPeerHandler.func2(0xc8200bd650)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/peer/handler.go:62 +0x2a
github.com/openblockchain/obc-peer/vendor/github.com/looplab/fsm.(*FSM).beforeEventCallbacks(0xc820133620, 0xc8200bd650, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/github.com/looplab/fsm/fsm.go:290 +0xb4
github.com/openblockchain/obc-peer/vendor/github.com/looplab/fsm.(*FSM).Event(0xc820133620, 0xb0f7e0, 0xa, 0xc8201276a0, 0x1, 0x1, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/github.com/looplab/fsm/fsm.go:242 +0x591
github.com/openblockchain/obc-peer/openchain/peer.(*Handler).HandleMessage(0xc820061c00, 0xc8201336b0, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/peer/handler.go:203 +0x5a9
github.com/openblockchain/obc-peer/openchain/peer.(*Peer).handleChat(0xc8201d6f90, 0x7ff581cb2e08, 0xc820133530, 0x7ff581cb3010, 0xc8201272e0, 0x10a9d00, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/peer/peer.go:354 +0x679
github.com/openblockchain/obc-peer/openchain/peer.(*Peer).Chat(0xc8201d6f90, 0x7ff581cb2fb8, 0xc8201272e0, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/peer/peer.go:165 +0xae
github.com/openblockchain/obc-peer/protos._Peer_Chat_Handler(0xab5200, 0xc8201d6f90, 0x7ff581cb2f70, 0xc82005ede0, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/protos/openchain.pb.go:324 +0xd8
github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc8201c8d80, 0x7ff581cb2c18, 0xc82008e3f0, 0xc8200b20c0, 0xc8201c3840, 0x10621e0, 0xc820133500, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/server.go:421 +0x2e4
github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc.(*Server).handleStream(0xc8201c8d80, 0x7ff581cb2c18, 0xc82008e3f0, 0xc8200b20c0, 0xc820133500)
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/server.go:471 +0x7f4
github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc.(*Server).Serve.func2.1.1(0xc8201c8d80, 0x7ff581cb2c18, 0xc82008e3f0, 0xc8200b20c0, 0xc820133500, 0xc8201271b0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/server.go:278 +0x49
created by github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc.(*Server).Serve.func2.1
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/server.go:280 +0x5ac

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7ff581cf3bd8, 0x72, 0xc820062140)
    /opt/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201ca0d0, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201ca0d0, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201ca070, 0x0, 0x7ff581cf4070, 0xc820085880)
    /usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820028330, 0xc8201ad760, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820028330, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc.(*Server).Serve(0xc8201c8d80, 0x7ff581cf2c58, 0xc820028330, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/server.go:224 +0x1c1
main.serve(0x10aaa00, 0x0, 0x0, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/main.go:367 +0xf56
main.glob.func1(0x1067c60, 0x10aaa00, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/main.go:68 +0x35
github.com/openblockchain/obc-peer/vendor/github.com/spf13/cobra.(*Command).execute(0x1067c60, 0x10aaa00, 0x0, 0x0, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/github.com/spf13/cobra/command.go:501 +0x869
github.com/openblockchain/obc-peer/vendor/github.com/spf13/cobra.(*Command).Execute(0x1067aa0, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/github.com/spf13/cobra/command.go:584 +0x46a
main.main()
    /opt/gopath/src/github.com/openblockchain/obc-peer/main.go:243 +0x1470

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /opt/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 6 [IO wait]:
net.runtime_pollWait(0x7ff581cf3b18, 0x72, 0xc820062140)
    /opt/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200bcfb0, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200bcfb0, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8200bcf50, 0x0, 0x7ff581cf4070, 0xc820085820)
    /usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820086200, 0xc8200c1d00, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc820086200, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc82005eae0, 0x7ff581cb2b08, 0xc820086200, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc82005eae0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0xc8201b2810, 0xc, 0x7ff581cb2ae0, 0xc820128410, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1967 +0x8f
github.com/openblockchain/obc-peer/openchain/rest.StartOpenchainRESTServer(0xc820028390, 0x10aaa00)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/rest/rest_api.go:308 +0x367
created by main.serve
    /opt/gopath/src/github.com/openblockchain/obc-peer/main.go:352 +0x94b

goroutine 21 [select]:
github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/transport.(*http2Server).controller(0xc82008e3f0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/transport/http2_server.go:611 +0x629
created by github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/transport.newHTTP2Server
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/transport/http2_server.go:133 +0x852

goroutine 22 [IO wait]:
net.runtime_pollWait(0x7ff581cf3a58, 0x72, 0xc820062140)
    /opt/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200bd020, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200bd020, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200bcfc0, 0xc82008e384, 0x9, 0x9, 0x0, 0x7ff581cae028, 0xc820062140)
    /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820086208, 0xc82008e384, 0x9, 0x9, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:172 +0xe4
io.ReadAtLeast(0x7ff581cb2bc8, 0xc820086208, 0xc82008e384, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
    /opt/go/src/io/io.go:298 +0xe6
io.ReadFull(0x7ff581cb2bc8, 0xc820086208, 0xc82008e384, 0x9, 0x9, 0x7, 0x0, 0x0)
    /opt/go/src/io/io.go:316 +0x62
github.com/openblockchain/obc-peer/vendor/golang.org/x/net/http2.readFrameHeader(0xc82008e384, 0x9, 0x9, 0x7ff581cb2bc8, 0xc820086208, 0x81000000, 0xc800000000, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/golang.org/x/net/http2/frame.go:227 +0xa5
github.com/openblockchain/obc-peer/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc82008e360, 0x0, 0x0, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/golang.org/x/net/http2/frame.go:372 +0xe6
github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/transport.(*framer).readFrame(0xc8201332f0, 0x0, 0x0, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/transport/http_util.go:450 +0x3d
github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc82008e3f0, 0xc820133380)
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/transport/http2_server.go:242 +0x663
github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc.(*Server).Serve.func2(0x7ff581cb2c18, 0xc82008e3f0, 0xc8201c8d80)
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/server.go:281 +0xcd
created by github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc.(*Server).Serve
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/server.go:286 +0xc78

goroutine 25 [select]:
github.com/openblockchain/obc-peer/openchain/peer.(*Handler).start(0xc820061c00, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/peer/handler.go:230 +0x408
created by github.com/openblockchain/obc-peer/openchain/peer.NewPeerHandler
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/peer/handler.go:84 +0xd2c
```

**Comment by ghaskins** [comment]
I am seeing this just running a non-validating peer manually outside of the unit tests

**Comment by srderson** [comment]
@jeffgarratt and @muralisrini said the test case needs to be reworked after issue #253 is completed. They are working on the issue #253 now.
