### ISSUE TITLE
Validator registration failure

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#399]
Working with the latest (as of this writing) commit on the master branch: 566a143d521430397eb5a568a7292ba346c4c03c
- Edit `openchain.yaml` to set `security.enabled` to `true`.
- Remove the `.obc-ca` and `production` directories.
- Launch `./obc-ca`
- Launch `./obc-peer peer --peer-chaincodedev`

Here's the error I'm getting:

```
16:40:09.713 [main] serve -> DEBU 001 Listen address not specified, using peer endpoint address
16:40:09.716 [eventhub_producer] AddEventType -> DEBU 002 registering block
16:40:09.716 [eventhub_producer] AddEventType -> DEBU 003 registering register
16:40:09.717 [eventhub_producer] start -> INFO 004 event processor started
16:40:09.717 [main] serve -> INFO 005 Running in chaincode development mode. Set consensus to NOOPS and user starts chaincode
16:40:09.718 [main] serve -> INFO 006 Security enabled status: true
16:40:09.718 [main] serve -> DEBU 007 Running as validating peer - installing consensus noops
16:40:09.718 [peer] NewPeerWithHandler -> DEBU 008 Registering validator with enroll ID: nepumuk
16:40:09.719 [CRYPTO] RegisterValidator -> INFO 009 Registering validator [nepumuk] with name [nepumuk]...
16:40:09.720 [CRYPTO] register -> ERRO 00a Failed initiliazing configuration [nepumuk] [Property not specified in configuration file. Please check that property is set: peer.pki.tlsca.paddr].
16:40:09.720 [CRYPTO] register -> ERRO 00b Failed registering [nepumuk]: %!(EXTRA *errors.errorString=Property not specified in configuration file. Please check that property is set: peer.pki.tlsca.paddr)
16:40:09.720 [CRYPTO] register -> ERRO 00c Failed registering%!(EXTRA string=nepumuk, *errors.errorString=Property not specified in configuration file. Please check that property is set: peer.pki.tlsca.paddr)
16:40:09.721 [CRYPTO] RegisterValidator -> ERRO 00d Failed registering validator [nepumuk] with name [nepumuk] [Property not specified in configuration file. Please check that property is set: peer.pki.tlsca.paddr].
16:40:09.721 [chaincode] NewChaincodeSupport -> INFO 00e Chaincode support using peerAddress: 0.0.0.0:30303
16:40:09.722 [db] createDBIfDBPathEmpty -> DEBU 00f Is db path [/var/openchain/production/db] empty [true]
16:40:09.723 [db] CreateDB -> DEBU 010 Creating DB at [/var/openchain/production/db]
16:40:09.729 [db] CreateDB -> DEBU 011 DB created at [/var/openchain/production/db]
16:40:09.735 [buckettree] Initialize -> INFO 012 Initializing bucket tree state implemetation with configurations &{maxGroupingAtEachLevel:10 lowestLevel:5 levelToNumBucketsMap:map[4:1001 3:101 2:11 1:2 0:1 5:10009] hashFunc:0x9d6e20}
16:40:09.736 [server] NewOpenchainServer -> INFO 013
Creating new OpenchainServer...
16:40:09.737 [main] serve -> INFO 014 Starting peer with id=name:"jdoe" , network id=dev, address=0.0.0.0:30303, discovery.rootnode=, validator=true
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4a5d47]

goroutine 1 [running]:
main.serve(0xc820168d80, 0x0, 0x1, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/main.go:407 +0x1457
main.glob.func1(0x1265480, 0xc820168d80, 0x0, 0x1)
    /opt/gopath/src/github.com/openblockchain/obc-peer/main.go:74 +0x35
github.com/openblockchain/obc-peer/vendor/github.com/spf13/cobra.(*Command).execute(0x1265480, 0xc820168d30, 0x1, 0x1, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/github.com/spf13/cobra/command.go:501 +0x869
github.com/openblockchain/obc-peer/vendor/github.com/spf13/cobra.(*Command).Execute(0x12652c0, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/github.com/spf13/cobra/command.go:584 +0x46a
main.main()
    /opt/gopath/src/github.com/openblockchain/obc-peer/main.go:272 +0x1691

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /opt/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 8 [chan receive]:
github.com/openblockchain/obc-peer/events/producer.(*eventProcessor).start(0xc820189b30)
    /opt/gopath/src/github.com/openblockchain/obc-peer/events/producer/events.go:72 +0xbe
created by github.com/openblockchain/obc-peer/events/producer.initializeEvents
    /opt/gopath/src/github.com/openblockchain/obc-peer/events/producer/events.go:120 +0x178

goroutine 9 [IO wait]:
net.runtime_pollWait(0x7f6de44fa6b8, 0x72, 0xc82000e1a0)
    /opt/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201a60d0, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201a60d0, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201a6070, 0x0, 0x7f6de44b4060, 0xc8201ac1e0)
    /usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8201f8058, 0xc8200a5d00, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc8201f8058, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc8201fa060, 0x7f6de44b4028, 0xc8201f8058, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc8201fa060, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0xc82015a120, 0xc, 0x7f6de44b4000, 0xc8201aa0d0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1967 +0x8f
github.com/openblockchain/obc-peer/openchain/rest.StartOpenchainRESTServer(0xc82002e560, 0xc8201d7540)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/rest/rest_api.go:384 +0x3ac
created by main.serve
    /opt/gopath/src/github.com/openblockchain/obc-peer/main.go:381 +0xef6

goroutine 10 [runnable]:
syscall.Syscall6(0x120, 0x3, 0xc82003aac0, 0xc82003aabc, 0x80800, 0x0, 0x0, 0xffffffffffffffff, 0x0, 0xb)
    /opt/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.accept4(0x3, 0xc82003aac0, 0xc82003aabc, 0x80800, 0x1, 0x0, 0x0)
    /opt/go/src/syscall/zsyscall_linux_amd64.go:1593 +0x72
syscall.Accept4(0x3, 0x80800, 0x5b2148, 0x0, 0x0, 0x0, 0x0)
    /opt/go/src/syscall/syscall_linux.go:453 +0x91
net.accept(0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/sock_cloexec.go:54 +0x67
net.(*netFD).accept(0xc820148f50, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/fd_unix.go:400 +0x16b
net.(*TCPListener).AcceptTCP(0xc82002e4b0, 0x4fc810, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc82002e4b0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc.(*Server).Serve(0xc82018df20, 0x7f6de44f98b8, 0xc82002e4b0, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/server.go:224 +0x1c1
main.serve.func1(0xc82018df20, 0x7f6de44f98b8, 0xc82002e4b0, 0xc8201e5380)
    /opt/gopath/src/github.com/openblockchain/obc-peer/main.go:401 +0x35
created by main.serve
    /opt/gopath/src/github.com/openblockchain/obc-peer/main.go:403 +0x132e
```

Seems there's an issue with the `peerServer.GetSecHelper()` call in line 407.

**Comment by adecaro** [comment]
Just issued a PR to address the bug. TLSCA configuration was missing in the openchain.yaml file.

**Comment by adecaro** [comment]
@kchristidis, if you don't want to wait the PR, you can just add the following lines to openchain.yaml:

```
peer:
    pki:
          tlsca:
              paddr: localhost:50951
```

This is enough to fix the bug you see.

**Comment by angrbrd** [comment]
@adecaro and @kchristidis , I have tested and confirm this fix. I just merged the associated PR.

Thanks.

**Comment by binhn** [comment]
we are opening too many ports on the security - i opened issue #404 to address
