### ISSUE TITLE
Network Setup doc instructions don't work as expected

### ISSUE THREAD

**Issue by frosenberg** [hyperledger-archives/fabric#406]
I'm following the docs here: 
https://github.com/openblockchain/obc-peer/blob/master/docs/Network%20Setup.md

Couple of issues: 
1. The doc says you should run it all on your Vagrant machine. So there should be a command to figure out the docker bridge IP as it is not necessarily the one used in the docs.
1. Launching the non-validating peer (which is non-docker), fails with a stacktrace:

```
vagrant@vagrant-ubuntu-trusty-64:/opt/gopath/src/github.com/openblockchain/obc-peer$ OPENCHAIN_PEER_LOGGING_LEVEL=DEBUG OPENCHAIN_PEER_DISCOVERY_ROOTNODE=172.17.0.3:30303 ./obc-peer peer
13:07:11.865 [main] serve -> DEBU 001 Running as validator - installing consensus noops
panic: DB path not specified in configuration file. Please check that property 'peer.db.path' is set

goroutine 1 [running]:
github.com/openblockchain/obc-peer/openchain/db.getDBPath(0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/db/db.go:162 +0xa8
github.com/openblockchain/obc-peer/openchain/db.createDBIfDBPathEmpty(0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/db/db.go:168 +0x36
github.com/openblockchain/obc-peer/openchain/db.GetDBHandle(0x30)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/db/db.go:94 +0x50
github.com/openblockchain/obc-peer/openchain/ledger.fetchBlockchainSizeFromDB(0xc61e4c, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/ledger/blockchain.go:235 +0x28
github.com/openblockchain/obc-peer/openchain/ledger.(*blockchain).init(0xc8201afb30, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/ledger/blockchain.go:59 +0x2b
github.com/openblockchain/obc-peer/openchain/ledger.getBlockchain(0xc8201b0be0, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/ledger/blockchain.go:49 +0x66
github.com/openblockchain/obc-peer/openchain/ledger.GetLedger.func1()
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/ledger/ledger.go:48 +0x1f
sync.(*Once).Do(0x10ddad8, 0xc653e0)
    /opt/go/src/sync/once.go:44 +0xe4
github.com/openblockchain/obc-peer/openchain/ledger.GetLedger(0xa60760, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/ledger/ledger.go:55 +0x3b
github.com/openblockchain/obc-peer/openchain/peer.NewPeerWithHandler(0xc653b8, 0xbeee60, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/peer/peer.go:174 +0x1f4
main.serve(0x10dda78, 0x0, 0x0, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/main.go:289 +0x741
main.glob.func1(0x109ac60, 0x10dda78, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/main.go:70 +0x35
github.com/openblockchain/obc-peer/vendor/github.com/spf13/cobra.(*Command).execute(0x109ac60, 0x10dda78, 0x0, 0x0, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/github.com/spf13/cobra/command.go:501 +0x869
github.com/openblockchain/obc-peer/vendor/github.com/spf13/cobra.(*Command).Execute(0x109aaa0, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/github.com/spf13/cobra/command.go:584 +0x46a
main.main()
    /opt/gopath/src/github.com/openblockchain/obc-peer/main.go:256 +0x1551

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /opt/go/src/runtime/asm_amd64.s:1696 +0x1
```

**Comment by srderson** [comment]
The https://github.com/openblockchain/obc-peer/blob/master/docs/Network%20Setup.md is out of date. @binhn should this document be updated or deleted? I'm not sure if the plan is to replace it with another doc.

**Comment by kletkeman** [comment]
I initiated this discussion recently on devscrum ... 

There are three copies of network setup instructions and this one is out of date and does not work. In the same obc-peer/docs folder, there is one that works called DevnetSetup.md that does work and in the obc-website/docs folder there is a verbatim copy of DevnetSetup.md called Setup_Network.md ... 

I have been asking on devscrum if there is a plan to set up a documentation strategy and naming convention and clean all this up? After all, there are at least three sets of documents that must eventually exist -- obc devs, app devs and systems engineers / deployment. What we have now is confusion between locations / copies and versions and this applies to a few other docs as well I believe.

**Comment by srderson** [comment]
Yes, documentation will be a focus in January. Having standardized naming conventions and document locations will be part of the effort. Details have not been finalized yet.
