### ISSUE TITLE
Error running test case crypto_test.go

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#526]
I hit the below error when running the entire test suite using the command

```
cd $GOPATH/src/github.com/openblockchain/obc-peer
go test -timeout=20m $(go list github.com/openblockchain/obc-peer/... | grep -v /vendor/)
```

It looks like it's creating a database under `.obc-peer/db`. It should not be using that path. There is a `/var/openchain/test/` path within that vagrant image for test case databases.

```
2016/01/20 15:29:19 15:29:19.649 [db] createDBIfDBPathEmpty [db.go:181] -> DEBU 6c4 Is db path [.obc-peer/db] empty [true]
2016/01/20 15:29:19 15:29:19.649 [db] CreateDB [db.go:58] -> DEBU 6c5 Creating DB at [.obc-peer/db]
Error opening DB Invalid argument: Column family not found: : blockchainCF
--- FAIL: TestValidatorDeployTransaction (0.65s)
    crypto_test.go:503: TestValidatorDeployTransaction with [%!s(int=0)]
panic: Could not open openchain db error = [Invalid argument: Column family not found: : blockchainCF] [recovered]
    panic: Could not open openchain db error = [Invalid argument: Column family not found: : blockchainCF]

goroutine 290 [running]:
testing.tRunner.func1(0xc820196ab0)
    /usr/local/go/src/testing/testing.go:450 +0x171
github.com/openblockchain/obc-peer/openchain/db.GetDBHandle(0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/db/db.go:106 +0x2cf
github.com/openblockchain/obc-peer/openchain/ledger.fetchBlockchainSizeFromDB(0x200, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/ledger/blockchain.go:304 +0x28
github.com/openblockchain/obc-peer/openchain/ledger.newBlockchain(0x0, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/ledger/blockchain.go:52 +0x2e
github.com/openblockchain/obc-peer/openchain/ledger.newLedger(0xc8203ffb48, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/ledger/ledger.go:70 +0x28
github.com/openblockchain/obc-peer/openchain/ledger.GetLedger.func1()
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/ledger/ledger.go:64 +0x1c
sync.(*Once).Do(0x1176c40, 0xcf9500)
    /opt/go/src/sync/once.go:44 +0xe4
github.com/openblockchain/obc-peer/openchain/ledger.GetLedger(0xc821e0, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/ledger/ledger.go:65 +0x3b
github.com/openblockchain/obc-peer/openchain/crypto.(*validatorImpl).verifyValidityPeriod(0xc820462c60, 0xc820283380, 0x1a, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/crypto/validator_impl.go:137 +0x229
github.com/openblockchain/obc-peer/openchain/crypto.(*validatorImpl).TransactionPreExecution(0xc820462c60, 0xc820283380, 0xc820283380, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/crypto/validator_impl.go:84 +0x1ab
github.com/openblockchain/obc-peer/openchain/crypto.TestValidatorDeployTransaction(0xc820196ab0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/crypto/crypto_test.go:518 +0x444
testing.tRunner(0xc820196ab0, 0x1135798)
    /usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
    /usr/local/go/src/testing/testing.go:561 +0x86d

goroutine 1 [chan receive]:
testing.RunTests(0xcf9f48, 0x1135600, 0x16, 0x16, 0x9ec201)
    /usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc820036f08, 0x26)
    /usr/local/go/src/testing/testing.go:494 +0x70
github.com/openblockchain/obc-peer/openchain/crypto.TestMain(0xc820036f08)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/crypto/crypto_test.go:99 +0xa40
main.main()
    github.com/openblockchain/obc-peer/openchain/crypto/_test/_testmain.go:94 +0x113

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /opt/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 6 [chan receive]:
database/sql.(*DB).connectionOpener(0xc820082fa0)
    /usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
    /usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 20 [IO wait]:
net.runtime_pollWait(0x7f37a5867c60, 0x72, 0xc82000e190)
    /opt/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820097090, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820097090, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820097030, 0x0, 0x7f37a5867d20, 0xc8204c4220)
    /usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200f6100, 0xc820038c98, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc8200f6100, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc.(*Server).Serve(0xc8204c03c0, 0x7f37a586f538, 0xc8200f6100, 0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/server.go:224 +0x1c1
github.com/openblockchain/obc-peer/openchain/crypto.initPKI()
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/crypto/crypto_test.go:809 +0x7e7
created by github.com/openblockchain/obc-peer/openchain/crypto.TestMain
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/crypto/crypto_test.go:67 +0x3c

goroutine 27 [chan receive]:
database/sql.(*DB).connectionOpener(0xc82014e6e0)
    /usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
    /usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 28 [chan receive]:
database/sql.(*DB).connectionOpener(0xc82014e960)
    /usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
    /usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 29 [sleep]:
time.Sleep(0x89d5f3200)
    /opt/go/src/runtime/time.go:59 +0xf9
github.com/openblockchain/obc-peer/obc-ca/obcca.updateValidityPeriod()
    /opt/gopath/src/github.com/openblockchain/obc-peer/obc-ca/obcca/validity_period.go:73 +0x1f9
created by github.com/openblockchain/obc-peer/obc-ca/obcca.(*TCA).startValidityPeriodUpdate
    /opt/gopath/src/github.com/openblockchain/obc-peer/obc-ca/obcca/tca.go:114 +0x39

goroutine 171 [chan receive]:
database/sql.(*DB).connectionOpener(0xc820544780)
    /usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
    /usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 220 [chan receive]:
database/sql.(*DB).connectionOpener(0xc8201dcaa0)
    /usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
    /usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 110 [chan receive]:
database/sql.(*DB).connectionOpener(0xc82054e960)
    /usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
    /usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 81 [chan receive]:
database/sql.(*DB).connectionOpener(0xc82014f7c0)
    /usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
    /usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 59 [chan receive]:
database/sql.(*DB).connectionOpener(0xc82014f4a0)
    /usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
    /usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 156 [chan receive]:
database/sql.(*DB).connectionOpener(0xc82054f180)
    /usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
    /usr/local/go/src/database/sql/sql.go:481 +0x336
FAIL    github.com/openblockchain/obc-peer/openchain/crypto 10.145s
```

**Comment by srderson** [comment]
Closing. Resolved in PR #532
