### ISSUE TITLE
obc-peer crashes with "index out of range" panic in ocbpbft.witnessCheckpoint

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#687]
Observed in:

```
commit e338d6a25865db96c4e6374168473965a2b39054
Merge: 67e2a10 15dcc91
Author: Binh Q Nguyen <binhn@us.ibm.com>
Date:   Mon Feb 15 12:10:54 2016 -0500
```

I have been stress-testing 4-node docker-compose networks today that use the "classic" PBFT. The setup is documented in #685. The network is set up, chaincode_example02 is deployed, and then simple "a gives b 1" transactions are invoked as fast as possible. These setups routinely crash. I have seen #676 appear in the logs, but observed what appears to be a new issue just now. This is from peer vp0, the peer targeted by the transactions:

```
[36m21:06:04.018 [devops] invokeOrQuery -> DEBU 583e[0m Sending invocation transaction (68971f80-2dc8-4428-bd41-885c8a0a5775) to validator
[36m21:06:04.018 [state] AddChangesForPersistence -> DEBU 583f[0m state.addChangesForPersistence()...start
[36m21:06:04.018 [buckettree] getAffectedBuckets -> DEBU 5840[0m Adding changed bucket [level=[5], bucketNumber=[8618]]
[36m21:06:04.018 [buckettree] getAffectedBuckets -> DEBU 5841[0m Adding changed bucket [level=[5], bucketNumber=[6083]]
[36m21:06:04.019 [buckettree] getAffectedBuckets -> DEBU 5842[0m Changed buckets are = [[level=[5], bucketNumber=[8618] level=[5], bucketNumber=[6083]]]
[36m21:06:04.019 [state] AddChangesForPersistence -> DEBU 5843[0m Adding state-delta corresponding to block number[98]
[36m21:06:04.019 [state] AddChangesForPersistence -> DEBU 5844[0m Not deleting previous state-delta. Block number [98] is smaller than historyStateDeltaSize [500]
[36m21:06:04.019 [state] AddChangesForPersistence -> DEBU 5845[0m state.addChangesForPersistence()...finished
[36m21:06:04.019 [ledger] resetForNextTxGroup -> DEBU 5846[0m resetting ledger state for next transaction batch
[36m21:06:04.019 [buckettree] ClearWorkingSet -> DEBU 5847[0m Enter - ClearWorkingSet()
[36m21:06:04.019 [consensus/obcpbft] startTimer -> DEBU 5848[0m Replica 0 starting new view timer for 10s
[36m21:06:04.019 [consensus/obcpbft] prepared -> DEBU 5849[0m Replica 0 prepare count for view=0/seqNo=99: 3
[36m21:06:04.019 [consensus/obcpbft] committed -> DEBU 584a[0m Replica 0 commit count for view=0/seqNo=99: 4
[36m21:06:04.019 [consensus/obcpbft] stopTimer -> DEBU 584b[0m Replica 0 stopping a running new view timer
21:06:04.019 [consensus/obcpbft] executeOne -> INFO 584c[0m Replica 0 executing/committing request for view=0/seqNo=99 and digest tqmTl9poynmJ7OnD3jpsPoraXkRQ87Ha9XuihHsNp4s3j0+LHaQlep8gd42na8evh1PQcA1yLuVjvoiGBOspug==
[36m21:06:04.019 [chaincode] LaunchChaincode -> DEBU 584d[0m chaincode is running(no need to launch) : d4d637637d6a61f4ad4a3cb8ce8f3c17ade203a6f6a826fd1115cd1e3569597dfc974e2f6e298f453cf67977b119a4ad98a089c5d83ea4916fd4b0ae66051770
[36m21:06:04.019 [state] TxBegin -> DEBU 584e[0m txBegin() for txUuid [6778e664-372c-4014-8524-f5e93fb819b2]
[36m21:06:04.019 [chaincode] sendExecuteMessage -> DEBU 584f[0m [6778e664]Inside sendExecuteMessage. Message TRANSACTION
[36m21:06:04.019 [chaincode] sendExecuteMessage -> DEBU 5850[0m [6778e664]sendExecuteMsg trigger event TRANSACTION
[36m21:06:04.019 [chaincode] processStream -> DEBU 5851[0m [6778e664]Move state message TRANSACTION
[36m21:06:04.019 [chaincode] HandleMessage -> DEBU 5852[0m [6778e664]Handling ChaincodeMessage of type: TRANSACTION in state ready
[36m21:06:04.019 [chaincode] processStream -> DEBU 5853[0m [6778e664]sending state message TRANSACTION
[36m21:06:04.019 [consensus/obcpbft] recvCheckpoint -> DEBU 5854[0m Replica 0 received checkpoint from replica 3, seqNo 110, digest +43eb6wm+RjdnUAZ3ESw4grQ85KvBZxARUcCxIPsaWEJqiuDEy3Z3cl4PVshbOm+PdDjiitirCqXS2/E5vmMTg==
[36m21:06:04.019 [chaincode] processStream -> DEBU 5856[0m [6778e664]Received message GET_STATE from shim
[36m21:06:04.019 [peer] DeregisterHandler -> DEBU 5857[0m Deregistered handler with key: name:"vp3" 
[36m21:06:04.019 [peer] sendTransactionsToThisPeer -> DEBU 5855[0m Marshalling transaction CHAINCODE_EXECUTE to send to self
panic: runtime error: index out of range

goroutine 19 [running]:
github.com/openblockchain/obc-peer/openchain/consensus/obcpbft.(*pbftCore).witnessCheckpoint(0xc820350500, 0xc8207b7f80)
    /go/src/github.com/openblockchain/obc-peer/openchain/consensus/obcpbft/pbft-core.go:942 +0x898
github.com/openblockchain/obc-peer/openchain/consensus/obcpbft.(*pbftCore).recvCheckpoint(0xc820350500, 0xc8207b7f80, 0x0, 0x0)
    /go/src/github.com/openblockchain/obc-peer/openchain/consensus/obcpbft/pbft-core.go:999 +0x271
github.com/openblockchain/obc-peer/openchain/consensus/obcpbft.(*pbftCore).recvMsgSync(0xc820350500, 0xc82336f720, 0x3, 0x0, 0x0)
    /go/src/github.com/openblockchain/obc-peer/openchain/consensus/obcpbft/pbft-core.go:528 +0xe24
github.com/openblockchain/obc-peer/openchain/consensus/obcpbft.(*pbftCore).receive(0xc820350500, 0xc8233c2cb0, 0x62, 0x62, 0x3, 0x0, 0x0)
    /go/src/github.com/openblockchain/obc-peer/openchain/consensus/obcpbft/pbft-core.go:487 +0x23e
github.com/openblockchain/obc-peer/openchain/consensus/obcpbft.(*obcClassic).RecvMsg(0xc820197b60, 0xc8208d1800, 0xc8203cbe60, 0x0, 0x0)
    /go/src/github.com/openblockchain/obc-peer/openchain/consensus/obcpbft/obc-classic.go:70 +0x548
github.com/openblockchain/obc-peer/openchain/consensus/helper.(*ConsensusHandler).HandleMessage(0xc820225b90, 0xc8208d1800, 0x0, 0x0)
    /go/src/github.com/openblockchain/obc-peer/openchain/consensus/helper/handler.go:74 +0x109
github.com/openblockchain/obc-peer/openchain/peer.(*PeerImpl).handleChat(0xc8202e2180, 0x7ff20779e360, 0xc820225b30, 0x7ff20779e510, 0xc8203ca010, 0x4e3d00, 0x0, 0x0)
    /go/src/github.com/openblockchain/obc-peer/openchain/peer/peer.go:636 +0x679
github.com/openblockchain/obc-peer/openchain/peer.(*PeerImpl).Chat(0xc8202e2180, 0x7ff20779e4b8, 0xc8203ca010, 0x0, 0x0)
    /go/src/github.com/openblockchain/obc-peer/openchain/peer/peer.go:277 +0xae
github.com/openblockchain/obc-peer/protos._Peer_Chat_Handler(0xd28980, 0xc8202e2180, 0x7ff20779e470, 0xc8201aa780, 0x0, 0x0)
    /go/src/github.com/openblockchain/obc-peer/protos/openchain.pb.go:601 +0xd8
github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc8202dc0c0, 0x7ff20779e1b0, 0xc8203c0090, 0xc8201e00c0, 0xc8202d9140, 0x1387fe0, 0xc820225b00, 0x0, 0x0)
    /go/src/github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/server.go:421 +0x2e4
github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc.(*Server).handleStream(0xc8202dc0c0, 0x7ff20779e1b0, 0xc8203c0090, 0xc8201e00c0, 0xc820225b00)
    /go/src/github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/server.go:471 +0x7f4
github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc.(*Server).Serve.func2.1.1(0xc8202dc0c0, 0x7ff20779e1b0, 0xc8203c0090, 0xc8201e00c0, 0xc820225b00, 0xc8203c2030)
    /go/src/github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/server.go:278 +0x49
created by github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc.(*Server).Serve.func2.1
    /go/src/github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/server.go:280 +0x5ac
```

The full log files are in the attached ZIP.
[logs.zip](https://github.com/openblockchain/obc-peer/files/133318/logs.zip)

These tests are being run on an X86 server outside of Vagrant. Full disclosure - for consistency with my testing on POWER I am using GOLANG 1.6RC2 on both X86 and POWER, so this could be a compiler issue.

**Comment by tuand27613** [comment]
@bcbrock , can you post what you're using for the client driver ?  @corecode is in the middle of doing some perf runs. If he doesn't get to this first,  I'll try to reproduce in the morning

**Comment by bcbrock** [comment]
@tuand27613, I use the attached Tcl script (which I had to rename to .txt to attach - please remove the file extension). This script runs chaincode_example02 transactions and checks the results. It can do transactions using the CLI, REST API or using `curl` to send REST API calls, but the built-in HTTP/REST method is the fastest. 
[driveEx02.txt](https://github.com/openblockchain/obc-peer/files/134412/driveEx02.txt)

To run this you will first need to need to 

```
sudo apt-get install -y tcl tclx
```

You will need to modify the docker-compose scripts attached in the ZIP above to send the logs to a well-known place for your system.

To recreate:

```
#Start the network
dcup dc_nosec_classic_4.yml
... Wait for the network to come up ...
# Deploy example 2 - This captures the chaincode name for the next script
eval `driveEx02 172.17.0.1 -deployOnly`
... Wait for the chaincode to deploy ...
# Run a single REST transaction - this should work
driveEx02 172.17.0.1 -rest
# Run 1000 REST transactions and allow 30 seconds before checking - This will probably crash
driveEx02 172.17.0.1 -rest -n 1000 -wait 30
# Run 4 copies of the driver each sending 1K transactions
driveEx02 172.17.0.1 -rest -n 1000 -wait 30 -multi 4
```

When I ran this just now it failed again with the index out of range error.

**Comment by jyellick** [comment]
@tuand27613 @bcbrock 

I see what is going on here, I'll put a patch together and submit a PR

**Comment by jyellick** [comment]
@bcbrock The way this issue is being triggered, is that a peer is falling just a little behind, then catching up, then falling a little behind again.  Although the crash is definitely a bug and is fixed in the PR above, this is probably indicative that the PBFT log size is insufficient.  You can increase the log size (and probably overall throughput) by increasing the checkpoint interval `general.K` in the obcpbft `config.yaml`.

@kchristidis Today, we set the log size statically to `instance.L = 2 * instance.K // log size`, this seems like it should be made configurable, or at least that multiplier of 2 should be made configurable.  I can open up an issue for this if you agree.

**Comment by tuand27613** [comment]
@jyellick,  this seems like the sort of interactions that we should document somewhere ( maybe protocol spec ? ) . We should document how to use the various options that we surface in config.yaml.

**Comment by jyellick** [comment]
@tuand27613 There is already some documentation in the config file itself (which I think is an intuitive place for it).  You can see the description for `general.K` as:

```
    # Checkpoint period is the maximum number of pbft requests that must be
    # re-processed in a view change. A smaller checkpoint period will decrease
    # the amount of time required to recover from an error, but will decrease
    # overall throughput in normal case operation.
```

Are you suggesting we have a separate `README.md` or something like that?

**Comment by tuand27613** [comment]
A lot of the text in config.yaml is descriptive.  We can probably describe in more details the why of setting something, e.g. increase request timeout if -blah blah-  or if you set L to x then this is what happens.

**Comment by kchristidis** [comment]
@jyellick Agree. `2*K` is from following the PBFT paper to the letter, but we can turn this into a parameter.

@tuand27613: Disagree. As @jyellick says, there is already a good enough amount of description in `config.yaml`. The user is expected to have some familiarity with the PBFT protocol.
