### ISSUE TITLE
after peer crash, database keeps crashing peer

### ISSUE THREAD

**Issue by corecode** [hyperledger-archives/fabric#720]
Observed several times during testing on my laptop (no vagrant):

```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x1b500d0546e0 pc=0x7fbcc5279fb5]

runtime stack:
runtime.throw(0xe91280, 0x2a)
    /usr/lib/go/src/runtime/panic.go:530 +0x90
runtime.sigpanic()
    /usr/lib/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 39 [syscall, locked to thread]:
runtime.cgocall(0xadc270, 0xc82004f668, 0x0)
    /usr/lib/go/src/runtime/cgocall.go:123 +0x11b fp=0xc82004f618 sp=0xc82004f5e8
github.com/openblockchain/obc-peer/vendor/github.com/tecbot/gorocksdb._Cfunc_rocksdb_get_cf(0x3a5c140, 0x3ae3780, 0x3a5c130, 0xc8202836a0, 0x8, 0xc8202836a8, 0xc82002e5c8, 0x0)
    github.com/openblockchain/obc-peer/vendor/github.com/tecbot/gorocksdb/_obj/_cgo_gotypes.go:988 +0x45 fp=0xc82004f668 sp=0xc82004f618
github.com/openblockchain/obc-peer/vendor/github.com/tecbot/gorocksdb.(*DB).GetCF(0xc82020d740, 0xc82002e5c0, 0xc82002e198, 0xc8202836a0, 0x8, 0x8, 0x0, 0x0, 0x0)
    /home/corecode/go/src/github.com/openblockchain/obc-peer/vendor/github.com/tecbot/gorocksdb/db.go:260 +0x3a0 fp=0xc82004f7a0 sp=0xc82004f668
github.com/openblockchain/obc-peer/openchain/db.(*OpenchainDB).get(0xc820230ab0, 0xc82002e198, 0xc8202836a0, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/corecode/go/src/github.com/openblockchain/obc-peer/openchain/db/db.go:253 +0xd4 fp=0xc82004f910 sp=0xc82004f7a0
github.com/openblockchain/obc-peer/openchain/db.(*OpenchainDB).GetFromBlockchainCF(0xc820230ab0, 0xc8202836a0, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/corecode/go/src/github.com/openblockchain/obc-peer/openchain/db/db.go:114 +0x75 fp=0xc82004f968 sp=0xc82004f910
github.com/openblockchain/obc-peer/openchain/ledger.fetchBlockFromDB(0x2cfb, 0xc8202fe200, 0x0, 0x0)
    /home/corecode/go/src/github.com/openblockchain/obc-peer/openchain/ledger/blockchain.go:287 +0x201 fp=0xc82004fa68 sp=0xc82004f968
github.com/openblockchain/obc-peer/openchain/ledger.(*blockchain).getBlock(0xc8201cefc0, 0x2cfb, 0xc8202fe200, 0x0, 0x0)
    /home/corecode/go/src/github.com/openblockchain/obc-peer/openchain/ledger/blockchain.go:102 +0x2d fp=0xc82004fa90 sp=0xc82004fa68
github.com/openblockchain/obc-peer/openchain/ledger.(*Ledger).GetBlockByNumber(0xc82020da60, 0x2cfb, 0xc8202fe200, 0x0, 0x0)
    /home/corecode/go/src/github.com/openblockchain/obc-peer/openchain/ledger/ledger.go:313 +0x70 fp=0xc82004fac0 sp=0xc82004fa90
github.com/openblockchain/obc-peer/openchain/ledger.(*Ledger).VerifyChain(0xc82020da60, 0x2d0a, 0x2cf6, 0xc82002e290, 0x0, 0x0)
    /home/corecode/go/src/github.com/openblockchain/obc-peer/openchain/ledger/ledger.go:364 +0x366 fp=0xc82004fb78 sp=0xc82004fac0
github.com/openblockchain/obc-peer/openchain/consensus/helper.(*Helper).VerifyBlockchain(0xc8201474c0, 0x2d0a, 0x2cf6, 0xc820280a80, 0x0, 0x0)
    /home/corecode/go/src/github.com/openblockchain/obc-peer/openchain/consensus/helper/helper.go:316 +0x163 fp=0xc82004fc00 sp=0xc82004fb78
github.com/openblockchain/obc-peer/openchain/consensus/statetransfer.(*StateTransferState).VerifyAndRecoverBlockchain(0xc820256dd0, 0xc8202e0001)
    /home/corecode/go/src/github.com/openblockchain/obc-peer/openchain/consensus/statetransfer/statetransfer.go:646 +0x10ea fp=0xc82004fdc0 sp=0xc82004fc00
github.com/openblockchain/obc-peer/openchain/consensus/statetransfer.(*StateTransferState).blockThread(0xc820256dd0)
    /home/corecode/go/src/github.com/openblockchain/obc-peer/openchain/consensus/statetransfer/statetransfer.go:694 +0x38f fp=0xc82004ff98 sp=0xc82004fdc0
runtime.goexit()
    /usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82004ffa0 sp=0xc82004ff98
created by github.com/openblockchain/obc-peer/openchain/consensus/statetransfer.NewStateTransferState
    /home/corecode/go/src/github.com/openblockchain/obc-peer/openchain/consensus/statetransfer/statetransfer.go:327 +0xad

```

**Comment by srderson** [comment]
Believe this was resolved via https://github.com/hyperledger/fabric/pull/786
