### ISSUE TITLE
Another PBFT Crash Signature

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#906]
Summary:

PBFT with classic consensus crashes in statemgmt.Marshal

Observed in:

commit f08ccce33b13f23eb1af97a43bf654aa48129794
Merge: ab0e167 bfecc0f
Author: tuand27613 tdang@us.ibm.com
Date:   Thu Mar 24 17:30:24 2016 -0400

```
Merge pull request #833 from jyellick/executor-split

obcpbft Executor split
```

Environment:

Docker-compose network of 4 validating peers; No security; PBFT Classic; All transactions sent to peer 0.

Recreate:
1. Install https://github.ibm.com/bcbrock/busywork as directed
2. `cd $(GOPATH)/src/github.ibm.com/bcbrock/busywork/counters`
3. `make stress2c`

Symptoms:

Peers 0 and 1 crash with what appears to be the same error. Peers 2 and 3 fail gracefully (gRPC errors) since peers 0 and 1 are dead.

```
VP0 Crash
---------

...
15:35:35.045 [consensus/obcpbft] RecvMsg -> INFO 6b59[0m New consensus request received
15:35:35.045 [rest] Invoke -> INFO 6b5a[0m Successfuly invoked chainCode with txuuid (57e123f8-0db8-4ebf-b188-cb3b7cf32aa1)
15:35:35.047 [rest] Invoke -> INFO 6b5b[0m REST invoking chaincode...
15:35:35.051 [consensus/obcpbft] RecvMsg -> INFO 6b5c[0m New consensus request received
15:35:35.051 [rest] Invoke -> INFO 6b5d[0m Successfuly invoked chainCode with txuuid (ea8a4c54-bb74-48a6-891d-fdb060eec613)
15:35:35.052 [rest] Invoke -> INFO 6b5e[0m REST invoking chaincode...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7cebac]

goroutine 105767 [running]:
panic(0xccdec0, 0xc820010080)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/openblockchain/obc-peer/openchain/ledger/statemgmt.(*StateDelta).Marshal(0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/openblockchain/obc-peer/openchain/ledger/statemgmt/state_delta.go:254 +0xdc
github.com/openblockchain/obc-peer/openchain/peer.(*Handler).sendStateDeltas(0xc8202d6690, 0xc8201fc290)
    /go/src/github.com/openblockchain/obc-peer/openchain/peer/handler.go:680 +0x508
created by github.com/openblockchain/obc-peer/openchain/peer.(*Handler).beforeSyncStateGetDeltas
    /go/src/github.com/openblockchain/obc-peer/openchain/peer/handler.go:652 +0x4e9

VP1 Crash
---------

...
15:35:33.042 [consensus/obcpbft] executeOne -> INFO 19be[0m Replica 1 executing/committing request for view=0/seqNo=6565 and digest DfpBWUSpFxzDTR9vl7jfi4+wWp2xmtZBnNF377YR6bOjdEJ0FoNjqIn55jljeZoNv2RziMXlMoUVxcGTSHtFVw==
15:35:33.046 [consensus/obcpbft] executeOne -> INFO 19bf[0m Replica 1 executing/committing request for view=0/seqNo=6566 and digest KHBsCXi81J0mNzgNLWqHWWq1U+5H50YHdZWSBThVcTmfy00s+PBxVBhcbPmf09jn4F7f9a+GoCBAG0cEA7N2wg==
15:35:33.050 [consensus/obcpbft] executeOne -> INFO 19c0[0m Replica 1 executing/committing request for view=0/seqNo=6567 and digest MY+ScepePbui1dVH+liLozzxCpxhDLfO9fXYI+5mdpfUAwg26kNy7Q3gug7fc23NMocX76RCWdALtW9+wy9hhA==
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7cebac]

goroutine 33129 [running]:
panic(0xccdec0, 0xc820014080)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/openblockchain/obc-peer/openchain/ledger/statemgmt.(*StateDelta).Marshal(0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/openblockchain/obc-peer/openchain/ledger/statemgmt/state_delta.go:254 +0xdc
github.com/openblockchain/obc-peer/openchain/peer.(*Handler).sendStateDeltas(0xc8203a0540, 0xc82ceee438)
    /go/src/github.com/openblockchain/obc-peer/openchain/peer/handler.go:680 +0x508
created by github.com/openblockchain/obc-peer/openchain/peer.(*Handler).beforeSyncStateGetDeltas
    /go/src/github.com/openblockchain/obc-peer/openchain/peer/handler.go:652 +0x4e9
```

**Comment by bcbrock** [comment]
FWIW, I've run Sieve consensus several times w/o errors, using the same irritation.

**Comment by jyellick** [comment]
There's a simple fix together for this, but holding off on the PR because of the pending Hyperledger move.

**Comment by bcbrock** [comment]
@jyellick - I can't validate whether this is fixed or not. I have moved to HyperLedger and am now at

```
commit 0b0e5714aca210868f1bf73482b13d072d391df3
Merge: 19337f3 860969b
Author: Sheehan Anderson <sranderson@gmail.com>
Date:   Fri Apr 8 22:15:29 2016 -0400

    Merge pull request #994 from ghaskins/devenv-tweaks

    Devenv tweaks
```

What I'm seeing now is that the peer network appears to simply "hang" after processing a relatively small number of transactions. There are also cases where the /chain/blocks/<n> API returns empty blocks.

If you think the crash that prompted this issue is fixed we can close it and I'll open a new one about the  hangs and other problems.

**Comment by jyellick** [comment]
@bcbrock Yes, I think this particular crash (nil pointer dereference) can be confidently said to be fixed.  The line where it occurred was fairly obvious and a nil check has been added, I think this can be closed.
