### ISSUE TITLE
TLS BDD failure

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#937]
@mrshah-at-ibm believe this started with PR #927. There are at least a couple of places where the variable was not updated. Specifically
openchain/peer/bddtests/docker-compose-2-tls-basic.yml
openchain/example/chaincode/asset_management/openchain.yaml

I tried updating these locally and the following BDD test still failed. Could you take a look?

```
  @tls
  Scenario: basic startup of 2 validating peers using TLS  # peer_basic.feature:551
    Given we compose "docker-compose-2-tls-basic.yml"      # steps/peer_basic_impl.py:85 0.969s
    When requesting "/chain" from "vp0"                    # steps/peer_basic_impl.py:98 0.003s
    Then I should get a JSON response with "height" = "1"  # steps/peer_basic_impl.py:108 0.008s
      Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1456, in run
          match.run(runner.context)
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "steps/peer_basic_impl.py", line 110, in step_impl
          assert attribute in context.response.json(), "Attribute not found in response (%s)" %(attribute)
        File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 793, in json
          return json.loads(self.text, **kwargs)
        File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
          return _default_decoder.decode(s)
        File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
          obj, end = self.raw_decode(s, idx=_w(s, 0).end())
        File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
          raise ValueError("No JSON object could be decoded")
      ValueError: No JSON object could be decoded

      Captured stdout:
      ['Creating', 'bddtests_vp0_1']
      ['Creating', 'bddtests_vp1_1']
      ['bddtests_vp0_1', 'bddtests_vp1_1']
      dockerComposeService = vp0
      container bddtests_vp0_1 has env = ['OPENCHAIN_LOGGING_LEVEL=DEBUG', 'OPENCHAIN_PEER_ADDRESSAUTODETECT=true', 'OPENCHAIN_PEER_ID=vp0', 'OPENCHAIN_VM_ENDPOINT=http://172.17.0.1:4243', 'OPENCHAIN_PEER_TLS_ENABLED=true', 'OPENCHAIN_PEER_TLS_SERVERHOSTOVERRIDE=OBC', 'OPENCHAIN_PEER_TLS_KEY_FILE=./openchain/peer/bddtests/tlsca.priv', 'OPENCHAIN_PEER_TLS_CERT_FILE=./openchain/peer/bddtests/tlsca.cert', 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/go/bin:/opt/gopath/bin', 'HOSTNAME=eb1fc0453f17', 'PWD=/', 'SHLVL=1', 'HOME=/root', 'GOROOT=/opt/go', 'GOPATH=/opt/gopath', '_=/usr/bin/printenv']
      dockerComposeService = vp1
      container bddtests_vp1_1 has env = ['OPENCHAIN_LOGGING_LEVEL=DEBUG', 'OPENCHAIN_PEER_ADDRESSAUTODETECT=true', 'OPENCHAIN_PEER_ID=vp1', 'OPENCHAIN_VM_ENDPOINT=http://172.17.0.1:4243', 'OPENCHAIN_PEER_TLS_ENABLED=true', 'OPENCHAIN_PEER_TLS_SERVERHOSTOVERRIDE=OBC', 'OPENCHAIN_PEER_DISCOVERY_ROOTNODE=vp0:30303', 'OPENCHAIN_PEER_TLS_KEY_FILE=./openchain/peer/bddtests/tlsca.priv', 'OPENCHAIN_PEER_TLS_CERT_FILE=./openchain/peer/bddtests/tlsca.cert', 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/go/bin:/opt/gopath/bin', 'HOSTNAME=eb1fc0453f17', 'PWD=/', 'SHLVL=1', 'HOME=/root', 'GOROOT=/opt/go', 'GOPATH=/opt/gopath', '_=/usr/bin/printenv']

      Requesting path = http://172.17.0.2:5000/chain


      Captured logging:
      INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 172.17.0.2

Decomposing with yaml 'docker-compose-2-tls-basic.yml' after scenario basic startup of 2 validating peers using TLS,
```

**Comment by srderson** [comment]
So this was actually introduced in PR #924. The problem is that the BDD tests always use http instead of https. The `basic startup of 2 validating peers using TLS` needs to be updated to use https.

**Comment by mrshah-at-work** [comment]
Yes, I will look into it

**Comment by mrshah-at-work** [comment]
@jeffgarratt you have put a fix (not verifying the certificate in the tests), correct?

**Comment by srderson** [comment]
Can confirm that the test is passing now.
